export const MALE_NAMES = [
  "Liam", "Noah", "Oliver", "Elijah", "James", "William", "Benjamin", "Lucas", "Henry", "Theodore",
  "Jack", "Levi", "Alexander", "Jackson", "Mateo", "Daniel", "Michael", "Mason", "Sebastian", "Ethan",
  "Logan", "Owen", "Samuel", "Jacob", "Asher", "Aiden", "John", "Joseph", "Wyatt", "David",
  "Leo", "Luke", "Julian", "Hudson", "Grayson", "Matthew", "Ezra", "Gabriel", "Carter", "Isaac",
  "Jayden", "Luca", "Anthony", "Dylan", "Lincoln", "Thomas", "Maverick", "Charles", "Josiah", "Brooks",
  "Jonathan", "Caleb", "Ryan", "Miles", "Wesley", "Nathan", "Christian", "Hunter", "Josh", "Eli",
  "Aaron", "Landon", "Jeremiah", "Harrison", "Cameron", "Ezekiel", "Colton", "Brayden", "Roman", "Ian",
  "Austin", "Adam", "Nicholas", "Dominic", "Greyson", "Jaxon", "Carson", "Evan", "Silas", "Ty",
  "Vincent", "Chase", "Cole", "Tyler", "Jason", "Gavin", "Zachary", "Harrison", "Victor", "Diego",
  "Luis", "Kevin", "Justin", "Brian", "Eric", "Edward", "Sean", "Colin", "Richard", "Peter",
  "Arthur", "Max", "Leon", "Felix", "Theo", "Oscar", "Finn", "Louis", "Hugo", "Emil",
  "Paul", "Anton", "Karl", "Mats", "Lukas", "Jonas", "Tim", "Jan", "Nils", "Mika",
  "Linus", "Tom", "Ben", "Lennard", "Jannis", "Marlon", "Till", "Jari", "Kian", "Lian",
  "Milan", "Levi", "Mael", "Lio", "Milo", "Nino", "Timo", "Nico", "Rico", "Enno",
  "Keno", "Tino", "Gino", "Pino", "Dino", "Rino", "Lino", "Mino", "Zeno", "Beno",
  "Arthur", "George", "Harry", "Charlie", "Alfie", "Freddie", "Archie", "Tommy", "Bobby", "Ronnie",
  "Reggie", "Frankie", "Louie", "Albert", "Stanley", "Arthur", "Edward", "Charles", "William", "Henry",
  "James", "George", "Thomas", "John", "Robert", "Richard", "Joseph", "David", "Michael", "Daniel",
  "Christopher", "Paul", "Mark", "Steven", "Andrew", "Kevin", "Brian", "Anthony", "Timothy", "Jason",
  "Matthew", "Gary", "Stephen", "Kenneth", "Colin", "Ian", "Peter", "Derek", "Martin", "Alan"
];

export const FEMALE_NAMES = [
  "Olivia", "Emma", "Charlotte", "Amelia", "Ava", "Sophia", "Isabella", "Mia", "Evelyn", "Harper",
  "Luna", "Camila", "Gianna", "Elizabeth", "Eleanor", "Ella", "Abigail", "Sofia", "Avery", "Scarlett",
  "Emily", "Aria", "Penelope", "Chloe", "Layla", "Mila", "Nora", "Hazel", "Madison", "Ellie",
  "Lily", "Nova", "Isla", "Grace", "Violet", "Aurora", "Riley", "Zoey", "Willow", "Emilia",
  "Stella", "Zoe", "Victoria", "Hannah", "Addison", "Lucy", "Eliana", "Ivy", "Everly", "Lillian",
  "Paisley", "Elena", "Naomi", "Maya", "Natalie", "Kinsley", "Delilah", "Claire", "Audrey", "Alice",
  "Savannah", "Ruby", "Serena", "Autumn", "Kennedy", "Samantha", "Sarah", "Josephine", "Allison", "Gabriella",
  "Madeline", "Cora", "Sadie", "Piper", "Lydia", "Clara", "Vivian", "Peyton", "Melody", "Julia",
  "Athena", "Maria", "Taylor", "Kylie", "Aubrey", "Sydney", "Jasmine", "Morgan", "Lauren", "Alyssa",
  "Kayla", "Rachel", "Megan", "Jessica", "Ashley", "Amanda", "Nicole", "Stephanie", "Heather", "Melissa",
  "Marie", "Sophie", "Maria", "Anna", "Laura", "Lea", "Sarah", "Julia", "Lena", "Lisa",
  "Katharina", "Johanna", "Lara", "Nele", "Pia", "Lina", "Clara", "Maja", "Hannah", "Emily",
  "Emma", "Mia", "Lilly", "Amelie", "Ida", "Leni", "Marlene", "Greta", "Frieda", "Mathilda",
  "Luisa", "Emilia", "Charlotte", "Marie", "Sophie", "Maria", "Anna", "Laura", "Lea", "Sarah",
  "Florence", "Alice", "Elsie", "Ivy", "Evelyn", "Edith", "Rose", "Daisy", "Lily", "Poppy",
  "Isla", "Ava", "Mia", "Evie", "Ruby", "Grace", "Freya", "Sienna", "Isabella", "Sophie",
  "Amelia", "Olivia", "Emily", "Jessica", "Chloe", "Megan", "Lauren", "Hannah", "Lucy", "Charlotte",
  "Sarah", "Emma", "Laura", "Katie", "Rebecca", "Amy", "Samantha", "Rachel", "Nicola", "Victoria"
];

export const COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo (Congo-Brazzaville)", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czechia", "Democratic Republic of the Congo", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Holy See", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine State", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
];

export const COUNTRY_DATA: Record<string, { cost: number, stability: number }> = {
  "Afghanistan": { cost: 3000, stability: 20 },
  "Albania": { cost: 8000, stability: 75 },
  "Algeria": { cost: 5000, stability: 65 },
  "Andorra": { cost: 25000, stability: 70 },
  "Angola": { cost: 5000, stability: 60 },
  "Antigua and Barbuda": { cost: 15000, stability: 75 },
  "Argentina": { cost: 7000, stability: 75 },
  "Armenia": { cost: 6000, stability: 75 },
  "Australia": { cost: 25000, stability: 80 },
  "Austria": { cost: 20000, stability: 80 },
  "Azerbaijan": { cost: 6000, stability: 70 },
  "Bahamas": { cost: 15000, stability: 75 },
  "Bahrain": { cost: 20000, stability: 65 },
  "Bangladesh": { cost: 4000, stability: 70 },
  "Barbados": { cost: 15000, stability: 80 },
  "Belarus": { cost: 6000, stability: 60 },
  "Belgium": { cost: 20000, stability: 75 },
  "Belize": { cost: 10000, stability: 80 },
  "Benin": { cost: 4000, stability: 70 },
  "Bhutan": { cost: 8000, stability: 65 },
  "Bolivia": { cost: 5000, stability: 75 },
  "Bosnia and Herzegovina": { cost: 8000, stability: 70 },
  "Botswana": { cost: 6000, stability: 75 },
  "Brazil": { cost: 8000, stability: 75 },
  "Brunei": { cost: 20000, stability: 65 },
  "Bulgaria": { cost: 10000, stability: 75 },
  "Burkina Faso": { cost: 3000, stability: 60 },
  "Burundi": { cost: 3000, stability: 30 },
  "Cabo Verde": { cost: 8000, stability: 65 },
  "Cambodia": { cost: 8000, stability: 65 },
  "Cameroon": { cost: 8000, stability: 65 },
  "Canada": { cost: 20000, stability: 80 },
  "Central African Republic": { cost: 3000, stability: 30 },
  "Chad": { cost: 3000, stability: 30 },
  "Chile": { cost: 20000, stability: 80 },
  "China": { cost: 8000, stability: 65 },
  "Colombia": { cost: 8000, stability: 65 },
  "Comoros": { cost: 8000, stability: 65 },
  "Congo (Congo-Brazzaville)": { cost: 8000, stability: 65 },
  "Costa Rica": { cost: 8000, stability: 65 },
  "Croatia": { cost: 20000, stability: 80 },
  "Cuba": { cost: 8000, stability: 65 },
  "Cyprus": { cost: 20000, stability: 80 },
  "Czechia": { cost: 20000, stability: 80 },
  "Democratic Republic of the Congo": { cost: 3000, stability: 30 },
  "Denmark": { cost: 20000, stability: 80 },
  "Djibouti": { cost: 8000, stability: 65 },
  "Dominica": { cost: 8000, stability: 65 },
  "Dominican Republic": { cost: 8000, stability: 65 },
  "Ecuador": { cost: 8000, stability: 65 },
  "Egypt": { cost: 8000, stability: 65 },
  "El Salvador": { cost: 8000, stability: 65 },
  "Equatorial Guinea": { cost: 8000, stability: 65 },
  "Eritrea": { cost: 3000, stability: 30 },
  "Estonia": { cost: 20000, stability: 80 },
  "Eswatini": { cost: 8000, stability: 65 },
  "Ethiopia": { cost: 3000, stability: 30 },
  "Fiji": { cost: 8000, stability: 65 },
  "Finland": { cost: 20000, stability: 80 },
  "France": { cost: 20000, stability: 80 },
  "Gabon": { cost: 8000, stability: 65 },
  "Gambia": { cost: 3000, stability: 30 },
  "Georgia": { cost: 8000, stability: 65 },
  "Germany": { cost: 20000, stability: 80 },
  "Ghana": { cost: 8000, stability: 65 },
  "Greece": { cost: 20000, stability: 80 },
  "Grenada": { cost: 8000, stability: 65 },
  "Guatemala": { cost: 8000, stability: 65 },
  "Guinea": { cost: 3000, stability: 30 },
  "Guinea-Bissau": { cost: 3000, stability: 30 },
  "Guyana": { cost: 8000, stability: 65 },
  "Haiti": { cost: 3000, stability: 30 },
  "Holy See": { cost: 8000, stability: 65 },
  "Honduras": { cost: 8000, stability: 65 },
  "Hungary": { cost: 20000, stability: 80 },
  "Iceland": { cost: 20000, stability: 80 },
  "India": { cost: 8000, stability: 65 },
  "Indonesia": { cost: 8000, stability: 65 },
  "Iran": { cost: 8000, stability: 65 },
  "Iraq": { cost: 8000, stability: 65 },
  "Ireland": { cost: 20000, stability: 80 },
  "Israel": { cost: 20000, stability: 80 },
  "Italy": { cost: 20000, stability: 80 },
  "Jamaica": { cost: 8000, stability: 65 },
  "Japan": { cost: 20000, stability: 80 },
  "Jordan": { cost: 8000, stability: 65 },
  "Kazakhstan": { cost: 8000, stability: 65 },
  "Kenya": { cost: 8000, stability: 65 },
  "Kiribati": { cost: 8000, stability: 65 },
  "Kuwait": { cost: 20000, stability: 80 },
  "Kyrgyzstan": { cost: 8000, stability: 65 },
  "Laos": { cost: 8000, stability: 65 },
  "Latvia": { cost: 20000, stability: 80 },
  "Lebanon": { cost: 8000, stability: 65 },
  "Lesotho": { cost: 8000, stability: 65 },
  "Liberia": { cost: 3000, stability: 30 },
  "Libya": { cost: 8000, stability: 65 },
  "Liechtenstein": { cost: 20000, stability: 80 },
  "Lithuania": { cost: 20000, stability: 80 },
  "Luxembourg": { cost: 20000, stability: 80 },
  "Madagascar": { cost: 3000, stability: 30 },
  "Malawi": { cost: 3000, stability: 30 },
  "Malaysia": { cost: 8000, stability: 65 },
  "Maldives": { cost: 8000, stability: 65 },
  "Mali": { cost: 3000, stability: 30 },
  "Malta": { cost: 20000, stability: 80 },
  "Marshall Islands": { cost: 8000, stability: 65 },
  "Mauritania": { cost: 8000, stability: 65 },
  "Mauritius": { cost: 8000, stability: 65 },
  "Mexico": { cost: 8000, stability: 65 },
  "Micronesia": { cost: 8000, stability: 65 },
  "Moldova": { cost: 8000, stability: 65 },
  "Monaco": { cost: 20000, stability: 80 },
  "Mongolia": { cost: 8000, stability: 65 },
  "Montenegro": { cost: 8000, stability: 65 },
  "Morocco": { cost: 8000, stability: 65 },
  "Mozambique": { cost: 3000, stability: 30 },
  "Myanmar": { cost: 8000, stability: 65 },
  "Namibia": { cost: 8000, stability: 65 },
  "Nauru": { cost: 8000, stability: 65 },
  "Nepal": { cost: 8000, stability: 65 },
  "Netherlands": { cost: 20000, stability: 80 },
  "New Zealand": { cost: 20000, stability: 80 },
  "Nicaragua": { cost: 8000, stability: 65 },
  "Niger": { cost: 3000, stability: 30 },
  "Nigeria": { cost: 8000, stability: 65 },
  "North Korea": { cost: 3000, stability: 30 },
  "North Macedonia": { cost: 8000, stability: 65 },
  "Norway": { cost: 20000, stability: 80 },
  "Oman": { cost: 20000, stability: 80 },
  "Pakistan": { cost: 8000, stability: 65 },
  "Palau": { cost: 8000, stability: 65 },
  "Palestine State": { cost: 8000, stability: 65 },
  "Panama": { cost: 20000, stability: 80 },
  "Papua New Guinea": { cost: 8000, stability: 65 },
  "Paraguay": { cost: 8000, stability: 65 },
  "Peru": { cost: 8000, stability: 65 },
  "Philippines": { cost: 8000, stability: 65 },
  "Poland": { cost: 20000, stability: 80 },
  "Portugal": { cost: 20000, stability: 80 },
  "Qatar": { cost: 20000, stability: 80 },
  "Romania": { cost: 20000, stability: 80 },
  "Russia": { cost: 8000, stability: 65 },
  "Rwanda": { cost: 3000, stability: 30 },
  "Saint Kitts and Nevis": { cost: 8000, stability: 65 },
  "Saint Lucia": { cost: 8000, stability: 65 },
  "Saint Vincent and the Grenadines": { cost: 8000, stability: 65 },
  "Samoa": { cost: 8000, stability: 65 },
  "San Marino": { cost: 20000, stability: 80 },
  "Sao Tome and Principe": { cost: 8000, stability: 65 },
  "Saudi Arabia": { cost: 20000, stability: 80 },
  "Senegal": { cost: 8000, stability: 65 },
  "Serbia": { cost: 8000, stability: 65 },
  "Seychelles": { cost: 20000, stability: 80 },
  "Sierra Leone": { cost: 3000, stability: 30 },
  "Singapore": { cost: 20000, stability: 80 },
  "Slovakia": { cost: 20000, stability: 80 },
  "Slovenia": { cost: 20000, stability: 80 },
  "Solomon Islands": { cost: 8000, stability: 65 },
  "Somalia": { cost: 3000, stability: 30 },
  "South Africa": { cost: 8000, stability: 65 },
  "South Korea": { cost: 20000, stability: 80 },
  "South Sudan": { cost: 3000, stability: 30 },
  "Spain": { cost: 20000, stability: 80 },
  "Sri Lanka": { cost: 8000, stability: 65 },
  "Sudan": { cost: 3000, stability: 30 },
  "Suriname": { cost: 8000, stability: 65 },
  "Sweden": { cost: 20000, stability: 80 },
  "Switzerland": { cost: 20000, stability: 80 },
  "Syria": { cost: 3000, stability: 30 },
  "Tajikistan": { cost: 8000, stability: 65 },
  "Tanzania": { cost: 8000, stability: 65 },
  "Thailand": { cost: 8000, stability: 65 },
  "Timor-Leste": { cost: 8000, stability: 65 },
  "Togo": { cost: 3000, stability: 30 },
  "Tonga": { cost: 8000, stability: 65 },
  "Trinidad and Tobago": { cost: 8000, stability: 65 },
  "Tunisia": { cost: 8000, stability: 65 },
  "Turkey": { cost: 8000, stability: 65 },
  "Turkmenistan": { cost: 8000, stability: 65 },
  "Tuvalu": { cost: 8000, stability: 65 },
  "Uganda": { cost: 3000, stability: 30 },
  "Ukraine": { cost: 8000, stability: 65 },
  "United Arab Emirates": { cost: 20000, stability: 80 },
  "United Kingdom": { cost: 20000, stability: 80 },
  "United States": { cost: 20000, stability: 80 },
  "Uruguay": { cost: 20000, stability: 80 },
  "Uzbekistan": { cost: 8000, stability: 65 },
  "Vanuatu": { cost: 8000, stability: 65 },
  "Venezuela": { cost: 8000, stability: 65 },
  "Vietnam": { cost: 8000, stability: 65 },
  "Yemen": { cost: 3000, stability: 30 },
  "Zambia": { cost: 3000, stability: 30 },
  "Zimbabwe": { cost: 3000, stability: 30 }
};

export const EDUCATION_COSTS = {
  'Community College': 10000,
  'University': 40000,
  'Medical School': 150000,
  'Law School': 100000,
  'Business School': 80000,
  'Flight School': 60000,
  'Maritime Academy': 50000,
  'Dental School': 120000,
  'Veterinary School': 100000,
  'Pharmacy School': 80000,
  'Space Training': 200000,
  'Graduate School': 50000,
  'Counseling School': 40000,
  'Planning School': 40000,
  'Intelligence Academy': 0,
  'Diplomatic Academy': 20000,
  'Police Academy': 5000,
  'Military Academy': 0,
  'Military Flight School': 0,
  'PhD Program': 60000,
  'Training Program': 2000,
  'Culinary School': 30000,
  'Certification': 1000,
  'Trade School': 15000
};

export const EDUCATION_DURATIONS: Record<string, number> = {
  'Community College': 2,
  'University': 4,
  'Medical School': 4,
  'Law School': 3,
  'Business School': 2,
  'Flight School': 1,
  'Maritime Academy': 4,
  'Dental School': 4,
  'Veterinary School': 4,
  'Pharmacy School': 4,
  'Space Training': 2,
  'Graduate School': 2,
  'Counseling School': 2,
  'Planning School': 2,
  'Intelligence Academy': 1,
  'Diplomatic Academy': 1,
  'Police Academy': 1,
  'Military Academy': 4,
  'Military Flight School': 1,
  'PhD Program': 4,
  'Training Program': 1,
  'Culinary School': 2,
  'Certification': 1,
  'Trade School': 2
};

export const UPGRADE_LEVELS = [
  { level: 1, name: 'Basic Improvements', costPct: 0.20, effectPct: 0.05 },
  { level: 2, name: 'Equipment Upgrade', costPct: 0.30, effectPct: 0.08 },
  { level: 3, name: 'Staff Expansion', costPct: 0.40, effectPct: 0.12 },
  { level: 4, name: 'Marketing Boost', costPct: 0.50, effectPct: 0.15 },
  { level: 5, name: 'Automation', costPct: 0.75, effectPct: 0.20 },
  { level: 6, name: 'Premium Expansion', costPct: 1.00, effectPct: 0.30 },
];

export const SMALL_PROPERTY_UPGRADES = [
  { id: 'sp1', name: 'Fresh Paint', revenueBoostPct: 0.02, costPct: 0.03 },
  { id: 'sp2', name: 'New Fixtures', revenueBoostPct: 0.03, costPct: 0.05 },
  { id: 'sp3', name: 'Landscaping', revenueBoostPct: 0.02, costPct: 0.04 },
  { id: 'sp4', name: 'Security System', revenueBoostPct: 0.03, costPct: 0.06 },
  { id: 'sp5', name: 'Energy Efficiency', revenueBoostPct: 0.04, costPct: 0.07 },
];

export const SMALL_BUSINESS_UPGRADES = [
  { id: 'sb1', name: 'Social Media Ads', revenueBoostPct: 0.02, costPct: 0.03 },
  { id: 'sb2', name: 'Customer Loyalty Program', revenueBoostPct: 0.03, costPct: 0.05 },
  { id: 'sb3', name: 'Employee Training', revenueBoostPct: 0.03, costPct: 0.04 },
  { id: 'sb4', name: 'Process Optimization', revenueBoostPct: 0.04, costPct: 0.06 },
  { id: 'sb5', name: 'Brand Refresh', revenueBoostPct: 0.02, costPct: 0.05 },
];

export const LARGE_PROPERTY_UPGRADES = [
  { id: 'lp1', name: 'Full Renovation', revenueBoostPct: 0.06, costPct: 0.12, valueBoostPct: 0.08 },
  { id: 'lp2', name: 'Smart Home System', revenueBoostPct: 0.05, costPct: 0.10, valueBoostPct: 0.06 },
  { id: 'lp3', name: 'Pool & Spa', revenueBoostPct: 0.07, costPct: 0.15, valueBoostPct: 0.10 },
  { id: 'lp4', name: 'Guest Suite Addition', revenueBoostPct: 0.08, costPct: 0.18, valueBoostPct: 0.12 },
  { id: 'lp5', name: 'Solar & Green Energy', revenueBoostPct: 0.06, costPct: 0.14, valueBoostPct: 0.07 },
  { id: 'lp6', name: 'Premium Kitchen Remodel', revenueBoostPct: 0.09, costPct: 0.20, valueBoostPct: 0.11 },
  { id: 'lp7', name: 'Luxury Landscaping & Terrace', revenueBoostPct: 0.10, costPct: 0.25, valueBoostPct: 0.14 },
];

export const LARGE_BUSINESS_UPGRADES = [
  { id: 'lb1', name: 'Flagship Location', revenueBoostPct: 0.06, costPct: 0.12, valueBoostPct: 0.08 },
  { id: 'lb2', name: 'Enterprise Software Suite', revenueBoostPct: 0.05, costPct: 0.10, valueBoostPct: 0.06 },
  { id: 'lb3', name: 'Regional Expansion', revenueBoostPct: 0.08, costPct: 0.18, valueBoostPct: 0.12 },
  { id: 'lb4', name: 'Celebrity Endorsement', revenueBoostPct: 0.07, costPct: 0.15, valueBoostPct: 0.09 },
  { id: 'lb5', name: 'R&D Department', revenueBoostPct: 0.09, costPct: 0.20, valueBoostPct: 0.11 },
  { id: 'lb6', name: 'International Distribution', revenueBoostPct: 0.08, costPct: 0.22, valueBoostPct: 0.13 },
  { id: 'lb7', name: 'Corporate Headquarters', revenueBoostPct: 0.10, costPct: 0.28, valueBoostPct: 0.15 },
];

export const WEDDING_VENUES = [
  { name: 'Local Courthouse', cost: 100, description: 'A simple, no-frills legal ceremony.' },
  { name: 'City Park', cost: 500, description: 'A lovely outdoor ceremony surrounded by nature.' },
  { name: 'Backyard Garden', cost: 1000, description: 'Intimate and personal at a family home.' },
  { name: 'Local Church', cost: 2000, description: 'A traditional religious ceremony.' },
  { name: 'Rustic Barn', cost: 5000, description: 'Charming countryside celebration.' },
  { name: 'Beachfront Resort', cost: 10000, description: 'Say your vows with the ocean breeze.' },
  { name: 'Historic Mansion', cost: 15000, description: 'Elegant and grand setting.' },
  { name: 'Botanical Garden', cost: 12000, description: 'Surrounded by exotic flowers and plants.' },
  { name: 'Vineyard Estate', cost: 18000, description: 'Romantic setting among the grapevines.' },
  { name: 'Luxury Hotel Ballroom', cost: 25000, description: 'Classic, opulent, and convenient.' },
  { name: 'Mountain Lodge', cost: 20000, description: 'Cozy and scenic with breathtaking views.' },
  { name: 'Art Museum', cost: 30000, description: 'Sophisticated and culturally rich.' },
  { name: 'Private Yacht', cost: 40000, description: 'Exclusive celebration on the water.' },
  { name: 'Tropical Island Destination', cost: 50000, description: 'A dream getaway wedding.' },
  { name: 'European Castle', cost: 75000, description: 'A fairytale wedding in a real castle.' },
  { name: 'Desert Oasis', cost: 15000, description: 'Unique and striking landscape.' },
  { name: 'Rooftop Lounge', cost: 22000, description: 'Modern chic with a city skyline view.' },
  { name: 'Aquarium', cost: 28000, description: 'Under the sea vibes with marine life.' },
  { name: 'Ski Resort', cost: 35000, description: 'A winter wonderland celebration.' },
  { name: 'Private Villa in Tuscany', cost: 60000, description: 'Romantic Italian countryside.' },
  { name: 'Safari Lodge in Kenya', cost: 80000, description: 'Wild and adventurous.' },
  { name: 'Ice Hotel in Sweden', cost: 45000, description: 'Chillingly beautiful and unique.' },
  { name: 'Treehouse Retreat', cost: 18000, description: 'Whimsical and close to nature.' },
  { name: 'Amusement Park', cost: 25000, description: 'Fun, thrilling, and unconventional.' },
  { name: 'Space Observatory', cost: 32000, description: 'A wedding under the stars.' },
  { name: 'Underground Cave', cost: 20000, description: 'Mysterious and dramatic.' },
  { name: 'Lighthouse', cost: 12000, description: 'Nautical and picturesque.' },
  { name: 'Helicopter Glacier Tour', cost: 55000, description: 'Extreme and unforgettable.' },
  { name: 'Overwater Bungalow in Bora Bora', cost: 90000, description: 'The ultimate luxury paradise.' },
  { name: 'Zero-Gravity Flight', cost: 150000, description: 'Literally floating down the aisle.' }
];
