import { BUSINESSES } from './businesses';
import { JOBS } from './jobs';
import type { BusinessDefinition, Job } from './types';

const expandedJobs: Job[] = [
  { id: 'job_253', title: 'Junior Accountant', salary: 52000, category: 'Finance', requirements: { education: 'University', smarts: 68, minCategoryExperience: 1 } },
  { id: 'job_254', title: 'Loan Officer', salary: 62000, category: 'Finance', requirements: { education: 'University', alternativeEducation: 'High School', smarts: 70, minCategoryExperience: 2 } },
  { id: 'job_255', title: 'Wealth Advisor', salary: 98000, category: 'Finance', requirements: { education: 'Business School', alternativeEducation: 'University', smarts: 84, minCategoryExperience: 5 } },
  { id: 'job_256', title: 'Mergers and Acquisitions Director', salary: 230000, category: 'Finance', requirements: { education: 'Business School', smarts: 97, minCategoryExperience: 15 } },
  { id: 'job_257', title: 'Bank Compliance Analyst', salary: 76000, category: 'Finance', requirements: { education: 'University', smarts: 80, minCategoryExperience: 3 } },
  { id: 'job_258', title: 'Junior Software Developer', salary: 72000, category: 'Technology', requirements: { education: 'University', smarts: 72, minCategoryExperience: 1 } },
  { id: 'job_259', title: 'Prompt Engineer', salary: 105000, category: 'Technology', requirements: { education: 'University', smarts: 86, minCategoryExperience: 3 } },
  { id: 'job_260', title: 'Computer Vision Engineer', salary: 138000, category: 'Technology', requirements: { education: 'University', smarts: 92, minCategoryExperience: 6 } },
  { id: 'job_261', title: 'AI Infrastructure Architect', salary: 185000, category: 'Technology', requirements: { education: 'University', smarts: 96, minCategoryExperience: 12 } },
  { id: 'job_262', title: 'Chief AI Officer', salary: 240000, category: 'Technology', requirements: { education: 'Business School', alternativeEducation: 'University', smarts: 98, minTotalExperience: 20 } },
  { id: 'job_263', title: 'Help Desk Technician', salary: 42000, category: 'Technology', requirements: { education: 'High School', smarts: 55, minCategoryExperience: 1 } },
  { id: 'job_264', title: 'Security Operations Analyst', salary: 88000, category: 'Technology', requirements: { education: 'University', alternativeEducation: 'Certification', smarts: 84, minCategoryExperience: 3 } },
  { id: 'job_265', title: 'Zero Trust Security Architect', salary: 165000, category: 'Technology', requirements: { education: 'University', smarts: 95, minCategoryExperience: 12 } },
  { id: 'job_266', title: 'Medical Assistant', salary: 43000, category: 'Health', requirements: { education: 'Certification', alternativeEducation: 'High School', smarts: 60, minCategoryExperience: 1 } },
  { id: 'job_267', title: 'Hospital Administrator', salary: 125000, category: 'Health', requirements: { education: 'Graduate School', smarts: 88, minCategoryExperience: 8 } },
  { id: 'job_268', title: 'Transplant Surgeon', salary: 260000, category: 'Health', requirements: { education: 'Medical School', smarts: 98, minCategoryExperience: 18 } },
  { id: 'job_269', title: 'Public Health Director', salary: 145000, category: 'Health', requirements: { education: 'Graduate School', smarts: 92, minCategoryExperience: 10 } },
  { id: 'job_270', title: 'Medical Device Sales Specialist', salary: 115000, category: 'Health', requirements: { education: 'University', smarts: 78, minCategoryExperience: 5 } },
  { id: 'job_271', title: 'Court Clerk', salary: 48000, category: 'Law', requirements: { education: 'High School', smarts: 64, minCategoryExperience: 1 } },
  { id: 'job_272', title: 'Contract Manager', salary: 92000, category: 'Law', requirements: { education: 'University', smarts: 82, minCategoryExperience: 5 } },
  { id: 'job_273', title: 'International Arbitration Lawyer', salary: 210000, category: 'Law', requirements: { education: 'Law School', smarts: 97, minCategoryExperience: 15 } },
  { id: 'job_274', title: 'Chief Legal Officer', salary: 245000, category: 'Law', requirements: { education: 'Law School', smarts: 98, minTotalExperience: 20 } },
  { id: 'job_275', title: 'Junior Civil Engineer', salary: 68000, category: 'Engineering', requirements: { education: 'University', smarts: 72, minCategoryExperience: 1 } },
  { id: 'job_276', title: 'Battery Systems Engineer', salary: 128000, category: 'Engineering', requirements: { education: 'University', smarts: 90, minCategoryExperience: 7 } },
  { id: 'job_277', title: 'Nuclear Engineer', salary: 155000, category: 'Engineering', requirements: { education: 'University', smarts: 94, minCategoryExperience: 10 } },
  { id: 'job_278', title: 'Chief Engineer', salary: 190000, category: 'Engineering', requirements: { education: 'University', smarts: 96, minTotalExperience: 20 } },
  { id: 'job_279', title: 'Preschool Teacher', salary: 38000, category: 'Education', requirements: { education: 'Certification', alternativeEducation: 'University', smarts: 60, minCategoryExperience: 1 } },
  { id: 'job_280', title: 'Instructional Designer', salary: 78000, category: 'Education', requirements: { education: 'University', smarts: 78, minCategoryExperience: 3 } },
  { id: 'job_281', title: 'Education Technology Director', salary: 125000, category: 'Education', requirements: { education: 'Graduate School', smarts: 90, minCategoryExperience: 10 } },
  { id: 'job_282', title: 'Celebrity Publicist', salary: 110000, category: 'Entertainment', requirements: { education: 'University', smarts: 82, popularity: 25, minCategoryExperience: 6 } },
  { id: 'job_283', title: 'Film Director', salary: 145000, category: 'Entertainment', requirements: { education: 'University', smarts: 88, popularity: 35, minCategoryExperience: 10 } },
  { id: 'job_284', title: 'Showrunner', salary: 180000, category: 'Entertainment', requirements: { education: 'University', smarts: 92, popularity: 40, minCategoryExperience: 15 } },
  { id: 'job_285', title: 'Tour Manager', salary: 85000, category: 'Entertainment', requirements: { education: 'High School', smarts: 72, minCategoryExperience: 5 } },
  { id: 'job_286', title: 'Shipping Coordinator', salary: 52000, category: 'Corporate', requirements: { education: 'High School', smarts: 62, minCategoryExperience: 1 } },
  { id: 'job_287', title: 'Cold Chain Logistics Manager', salary: 102000, category: 'Corporate', requirements: { education: 'University', smarts: 82, minCategoryExperience: 6 } },
  { id: 'job_288', title: 'Global Trade Compliance Director', salary: 155000, category: 'Corporate', requirements: { education: 'Business School', alternativeEducation: 'University', smarts: 92, minCategoryExperience: 12 } },
  { id: 'job_289', title: 'Rail Operations Planner', salary: 84000, category: 'Public Service', requirements: { education: 'University', smarts: 78, minCategoryExperience: 4 } },
  { id: 'job_290', title: 'Environmental Policy Analyst', salary: 82000, category: 'Public Service', requirements: { education: 'University', smarts: 82, minCategoryExperience: 3 } },
  { id: 'job_291', title: 'City Transit Commissioner', salary: 150000, category: 'Public Service', requirements: { education: 'Graduate School', smarts: 92, minTotalExperience: 18 } },
  { id: 'job_292', title: 'Research Lab Technician', salary: 54000, category: 'Science', requirements: { education: 'University', smarts: 72, minCategoryExperience: 1 } },
  { id: 'job_293', title: 'Materials Scientist', salary: 118000, category: 'Science', requirements: { education: 'Graduate School', smarts: 90, minCategoryExperience: 7 } },
  { id: 'job_294', title: 'Quantum Hardware Scientist', salary: 175000, category: 'Science', requirements: { education: 'PhD Program', smarts: 98, minCategoryExperience: 12 } },
  { id: 'job_295', title: 'Airport Ramp Agent', salary: 42000, category: 'Aviation', requirements: { education: 'High School', smarts: 55, health: 45, minCategoryExperience: 1 } },
  { id: 'job_296', title: 'Commercial Drone Fleet Manager', salary: 98000, category: 'Aviation', requirements: { education: 'Certification', alternativeEducation: 'University', smarts: 82, minCategoryExperience: 5 } },
  { id: 'job_297', title: 'Airline Safety Director', salary: 170000, category: 'Aviation', requirements: { education: 'Flight School', alternativeEducation: 'University', smarts: 94, minCategoryExperience: 15 } },
  { id: 'job_298', title: 'Deckhand', salary: 42000, category: 'Maritime', requirements: { education: 'High School', smarts: 55, health: 45, minCategoryExperience: 1 } },
  { id: 'job_299', title: 'Offshore Wind Vessel Captain', salary: 135000, category: 'Maritime', requirements: { education: 'Maritime Academy', smarts: 88, minCategoryExperience: 10 } },
  { id: 'job_300', title: 'Global Shipping Executive', salary: 220000, category: 'Maritime', requirements: { education: 'Business School', alternativeEducation: 'Maritime Academy', smarts: 96, minTotalExperience: 20 } },
];

const upgradesFor = (businessName: string) => [
  { id: 'u1', name: `${businessName} Marketing`, costMultiplier: 0.2, profitBoost: 0.05 },
  { id: 'u2', name: 'Operational Systems', costMultiplier: 0.4, profitBoost: 0.1 },
  { id: 'u3', name: 'Premium Expansion', costMultiplier: 0.6, profitBoost: 0.15 },
  { id: 'u4', name: 'Multi-market Scaling', costMultiplier: 1.0, profitBoost: 0.25 },
];

const business = (id: string, name: string, category: BusinessDefinition['category'], basePrice: number, riskLevel: BusinessDefinition['riskLevel']): BusinessDefinition => ({
  id,
  name,
  category,
  basePrice,
  riskLevel,
  uniqueUpgrades: upgradesFor(name),
});

const expandedBusinesses: BusinessDefinition[] = [
  business('exp_small_1', 'Neighborhood ramen shop', 'Small', 95000, 'Medium'),
  business('exp_small_2', 'Mobile coffee roaster', 'Small', 65000, 'Low'),
  business('exp_small_3', 'Specialty cookie bakery', 'Small', 70000, 'Low'),
  business('exp_small_4', 'Local meal kit brand', 'Small', 110000, 'Medium'),
  business('exp_small_5', 'Pop-up sneaker store', 'Small', 85000, 'Medium'),
  business('exp_small_6', 'Vintage camera shop', 'Small', 45000, 'Low'),
  business('exp_small_7', 'Home health aide agency', 'Small', 120000, 'Medium'),
  business('exp_small_8', 'Mobile IV clinic', 'Small', 140000, 'Medium'),
  business('exp_small_9', 'Boutique cybersecurity consultancy', 'Small', 150000, 'Medium'),
  business('exp_small_10', 'AI automation studio', 'Small', 175000, 'Medium'),
  business('exp_small_11', 'Local creator merch store', 'Small', 60000, 'Low'),
  business('exp_small_12', 'Podcast editing service', 'Small', 25000, 'Low'),
  business('exp_small_13', 'Micro logistics courier fleet', 'Small', 160000, 'Medium'),
  business('exp_small_14', 'Cold storage rental unit', 'Small', 200000, 'Medium'),
  business('exp_small_15', 'Boutique language app', 'Small', 130000, 'Medium'),
  business('exp_small_16', 'Pet subscription box', 'Small', 90000, 'Medium'),
  business('exp_small_17', 'Remote bookkeeping firm', 'Small', 50000, 'Low'),
  business('exp_small_18', 'Niche job board', 'Small', 80000, 'Medium'),
  business('exp_small_19', 'Mobile esports coaching club', 'Small', 75000, 'Medium'),
  business('exp_small_20', 'Urban mushroom farm', 'Small', 115000, 'Medium'),
  business('exp_medium_1', 'Regional grocery delivery platform', 'Medium', 1800000, 'High'),
  business('exp_medium_2', 'Ghost kitchen network', 'Medium', 2200000, 'High'),
  business('exp_medium_3', 'Boutique airline lounge operator', 'Medium', 1600000, 'Medium'),
  business('exp_medium_4', 'Electric scooter sharing company', 'Medium', 2400000, 'High'),
  business('exp_medium_5', 'Online bank startup', 'Medium', 3500000, 'Very High'),
  business('exp_medium_6', 'Specialty insurance brokerage', 'Medium', 1200000, 'Medium'),
  business('exp_medium_7', 'Creator economy platform', 'Medium', 2800000, 'High'),
  business('exp_medium_8', 'Regional podcast network', 'Medium', 900000, 'Medium'),
  business('exp_medium_9', 'Virtual care provider', 'Medium', 2600000, 'High'),
  business('exp_medium_10', 'Medical device distributor', 'Medium', 3100000, 'Medium'),
  business('exp_medium_11', 'Robotics warehouse integrator', 'Medium', 4200000, 'High'),
  business('exp_medium_12', 'Battery recycling company', 'Medium', 3800000, 'High'),
  business('exp_medium_13', 'Regional solar utility', 'Medium', 4600000, 'Medium'),
  business('exp_medium_14', 'Luxury pet hotel chain', 'Medium', 1400000, 'Medium'),
  business('exp_medium_15', 'Private tutoring marketplace', 'Medium', 1100000, 'Medium'),
  business('exp_medium_16', 'Digital law firm', 'Medium', 1700000, 'Medium'),
  business('exp_medium_17', 'Cloud kitchen franchise', 'Medium', 2500000, 'High'),
  business('exp_medium_18', 'Regional event ticketing platform', 'Medium', 2000000, 'High'),
  business('exp_medium_19', 'Premium camping resort chain', 'Medium', 3000000, 'Medium'),
  business('exp_medium_20', 'Smart home installation chain', 'Medium', 1900000, 'Medium'),
  business('exp_large_1', 'National e-commerce marketplace', 'Large', 120000000, 'High'),
  business('exp_large_2', 'Autonomous taxi network', 'Large', 180000000, 'Very High'),
  business('exp_large_3', 'Satellite internet provider', 'Large', 220000000, 'Very High'),
  business('exp_large_4', 'National streaming service', 'Large', 150000000, 'High'),
  business('exp_large_5', 'Electric battery manufacturer', 'Large', 175000000, 'High'),
  business('exp_large_6', 'Semiconductor fabrication plant', 'Large', 450000000, 'Very High'),
  business('exp_large_7', 'National hospital system', 'Large', 250000000, 'High'),
  business('exp_large_8', 'Private university system', 'Large', 160000000, 'Medium'),
  business('exp_large_9', 'Sports broadcasting network', 'Large', 110000000, 'High'),
  business('exp_large_10', 'Global freight airline', 'Large', 300000000, 'High'),
  business('exp_large_11', 'Electric vehicle charging network', 'Large', 95000000, 'Medium'),
  business('exp_large_12', 'National pharmacy chain', 'Large', 140000000, 'Medium'),
  business('exp_large_13', 'Cloud gaming platform', 'Large', 125000000, 'Very High'),
  business('exp_large_14', 'Fintech payments network', 'Large', 200000000, 'Very High'),
  business('exp_large_15', 'Luxury resort portfolio', 'Large', 130000000, 'High'),
  business('exp_large_16', 'Smart appliance manufacturer', 'Large', 90000000, 'High'),
  business('exp_large_17', 'Industrial robotics manufacturer', 'Large', 210000000, 'High'),
  business('exp_large_18', 'Major game publisher', 'Large', 240000000, 'Very High'),
  business('exp_large_19', 'International food delivery app', 'Large', 175000000, 'Very High'),
  business('exp_large_20', 'Global hotel booking platform', 'Large', 190000000, 'High'),
  business('exp_ultra_1', 'Global AI chip company', 'Ultra Rich', 6000000000, 'Very High'),
  business('exp_ultra_2', 'Worldwide autonomous car company', 'Ultra Rich', 5500000000, 'Very High'),
  business('exp_ultra_3', 'Global cloud marketplace', 'Ultra Rich', 6500000000, 'Very High'),
  business('exp_ultra_4', 'International streaming universe', 'Ultra Rich', 4200000000, 'High'),
  business('exp_ultra_5', 'Global luxury travel group', 'Ultra Rich', 3000000000, 'High'),
  business('exp_ultra_6', 'Worldwide grocery corporation', 'Ultra Rich', 3800000000, 'Medium'),
  business('exp_ultra_7', 'Global medical technology group', 'Ultra Rich', 4500000000, 'High'),
  business('exp_ultra_8', 'International payments network', 'Ultra Rich', 5000000000, 'Very High'),
  business('exp_ultra_9', 'Global cyber defense company', 'Ultra Rich', 3400000000, 'High'),
  business('exp_ultra_10', 'Orbital logistics corporation', 'Ultra Rich', 7000000000, 'Very High'),
  business('exp_ultra_11', 'Worldwide sports media league', 'Ultra Rich', 3600000000, 'High'),
  business('exp_ultra_12', 'Global robotics automation group', 'Ultra Rich', 4800000000, 'Very High'),
  business('exp_ultra_13', 'International electric grid operator', 'Ultra Rich', 5200000000, 'High'),
  business('exp_ultra_14', 'Planet-scale education platform', 'Ultra Rich', 2800000000, 'Medium'),
  business('exp_ultra_15', 'Global creator platform', 'Ultra Rich', 3900000000, 'Very High'),
];

const existingJobIds = new Set(JOBS.map((job) => job.id));
JOBS.push(...expandedJobs.filter((job) => !existingJobIds.has(job.id)));

const existingBusinessNames = new Set(BUSINESSES.map((businessItem) => businessItem.name));
BUSINESSES.push(...expandedBusinesses.filter((businessItem) => !existingBusinessNames.has(businessItem.name)));
