import { Job } from './types';

export const JOBS: Job[] = [
  // 🟢 ENTRY-LEVEL / INTERNSHIPS (no education or experience needed)
  { id: 'entry_1', title: 'Grocery Bagger', salary: 18000, category: 'Service', requirements: { education: 'None', smarts: 5 } },
  { id: 'entry_2', title: 'Fast Food Worker', salary: 20000, category: 'Service', requirements: { education: 'None', smarts: 5 } },
  { id: 'entry_3', title: 'Dog Walker', salary: 16000, category: 'Service', requirements: { education: 'None', smarts: 5 } },
  { id: 'entry_4', title: 'Newspaper Delivery', salary: 15000, category: 'Service', requirements: { education: 'None', smarts: 5 } },
  { id: 'entry_5', title: 'Car Wash Attendant', salary: 18000, category: 'Service', requirements: { education: 'None', smarts: 5 } },
  { id: 'entry_6', title: 'Babysitter', salary: 16000, category: 'Service', requirements: { education: 'None', smarts: 10 } },
  { id: 'entry_7', title: 'Mover', salary: 22000, category: 'Service', requirements: { education: 'None', smarts: 5, health: 30 } },
  { id: 'entry_8', title: 'Food Delivery Driver', salary: 22000, category: 'Service', requirements: { education: 'None', smarts: 10 } },
  { id: 'intern_1', title: 'Office Intern', salary: 20000, category: 'Corporate', requirements: { education: 'High School', smarts: 25 } },
  { id: 'intern_2', title: 'Tech Intern', salary: 25000, category: 'Technology', requirements: { education: 'High School', smarts: 40 } },
  { id: 'intern_3', title: 'Hospital Volunteer', salary: 12000, category: 'Health', requirements: { education: 'High School', smarts: 30 } },
  { id: 'intern_4', title: 'Legal Clerk', salary: 22000, category: 'Law', requirements: { education: 'High School', smarts: 35 } },
  { id: 'intern_5', title: 'Bank Teller', salary: 28000, category: 'Finance', requirements: { education: 'High School', smarts: 30 } },
  { id: 'intern_6', title: 'Lab Assistant', salary: 24000, category: 'Science', requirements: { education: 'High School', smarts: 40 } },
  { id: 'intern_7', title: 'Media Intern', salary: 20000, category: 'Media', requirements: { education: 'High School', smarts: 25 } },
  { id: 'intern_8', title: 'Teaching Assistant', salary: 22000, category: 'Education', requirements: { education: 'High School', smarts: 35 } },

  // 🟢 SERVICE & EVERYDAY JOBS
  { id: 'job_1', title: 'Barista', salary: 25000, category: 'Service', requirements: { education: 'High School', smarts: 30 } },
  { id: 'job_2', title: 'Hotel Receptionist', salary: 30000, category: 'Service', requirements: { education: 'High School', smarts: 35 } },
  { id: 'job_3', title: 'Tour Guide', salary: 32000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_4', title: 'Flight Attendant', salary: 45000, category: 'Service', requirements: { education: 'Training Program', smarts: 45 } },
  { id: 'job_5', title: 'Travel Agent', salary: 40000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_6', title: 'Call Center Supervisor', salary: 45000, category: 'Service', requirements: { education: 'High School', smarts: 45 } },
  { id: 'job_7', title: 'Customer Support Rep', salary: 35000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_8', title: 'Retail Supervisor', salary: 42000, category: 'Service', requirements: { education: 'High School', smarts: 45 } },
  { id: 'job_9', title: 'Store Clerk', salary: 28000, category: 'Service', requirements: { education: 'None', smarts: 20 } },
  { id: 'job_10', title: 'Fast Food Manager', salary: 45000, category: 'Service', requirements: { education: 'High School', smarts: 45 } },
  { id: 'job_11', title: 'Dishwasher', salary: 24000, category: 'Service', requirements: { education: 'None', smarts: 10 } },
  { id: 'job_12', title: 'Line Cook', salary: 35000, category: 'Service', requirements: { education: 'Culinary School', smarts: 30 } },
  { id: 'job_13', title: 'Kitchen Manager', salary: 50000, category: 'Service', requirements: { education: 'Culinary School', smarts: 40 } },
  { id: 'job_14', title: 'Housekeeper', salary: 28000, category: 'Service', requirements: { education: 'None', smarts: 20 } },
  { id: 'job_15', title: 'Concierge', salary: 38000, category: 'Service', requirements: { education: 'High School', smarts: 45 } },
  { id: 'job_16', title: 'Event Staff', salary: 26000, category: 'Service', requirements: { education: 'None', smarts: 20 } },
  { id: 'job_17', title: 'Security Supervisor', salary: 45000, category: 'Service', requirements: { education: 'Certification', smarts: 40 } },
  { id: 'job_18', title: 'Parking Manager', salary: 40000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_19', title: 'Warehouse Manager', salary: 55000, category: 'Service', requirements: { education: 'High School', smarts: 45 } },
  { id: 'job_20', title: 'Inventory Manager', salary: 50000, category: 'Service', requirements: { education: 'High School', smarts: 45 } },
  { id: 'job_21', title: 'Delivery Manager', salary: 48000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_22', title: 'Taxi Dispatcher', salary: 35000, category: 'Service', requirements: { education: 'High School', smarts: 35 } },
  { id: 'job_23', title: 'Bus Coordinator', salary: 42000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_24', title: 'Postal Worker', salary: 40000, category: 'Service', requirements: { education: 'High School', smarts: 35 } },
  { id: 'job_25', title: 'Courier Manager', salary: 45000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_26', title: 'Cleaner Supervisor', salary: 35000, category: 'Service', requirements: { education: 'None', smarts: 30 } },
  { id: 'job_27', title: 'Gym Staff', salary: 28000, category: 'Service', requirements: { education: 'High School', smarts: 30 } },
  { id: 'job_28', title: 'Lifeguard Supervisor', salary: 38000, category: 'Service', requirements: { education: 'Certification', smarts: 40 } },
  { id: 'job_29', title: 'Pet Groomer', salary: 32000, category: 'Service', requirements: { education: 'Trade School', smarts: 30 } },
  { id: 'job_30', title: 'Dog Trainer', salary: 35000, category: 'Service', requirements: { education: 'Certification', smarts: 35 } },
  { id: 'job_31', title: 'Florist', salary: 30000, category: 'Service', requirements: { education: 'Trade School', smarts: 30 } },
  { id: 'job_32', title: 'Baker', salary: 35000, category: 'Service', requirements: { education: 'Culinary School', smarts: 35 } },
  { id: 'job_33', title: 'Butcher', salary: 38000, category: 'Service', requirements: { education: 'None', smarts: 35 } },
  { id: 'job_34', title: 'Tailor', salary: 34000, category: 'Service', requirements: { education: 'None', smarts: 35 } },
  { id: 'job_35', title: 'Shoe Repair Specialist', salary: 32000, category: 'Service', requirements: { education: 'None', smarts: 30 } },
  { id: 'job_36', title: 'Locksmith', salary: 45000, category: 'Service', requirements: { education: 'None', smarts: 40 } },
  { id: 'job_37', title: 'Car Detailer', salary: 30000, category: 'Service', requirements: { education: 'None', smarts: 25 } },
  { id: 'job_38', title: 'Valet Manager', salary: 40000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_39', title: 'Parking Attendant', salary: 25000, category: 'Service', requirements: { education: 'None', smarts: 20 } },
  { id: 'job_40', title: 'Ticket Inspector', salary: 35000, category: 'Service', requirements: { education: 'High School', smarts: 35 } },
  { id: 'job_41', title: 'Cinema Manager', salary: 45000, category: 'Service', requirements: { education: 'High School', smarts: 45 } },
  { id: 'job_42', title: 'Arcade Manager', salary: 42000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_43', title: 'Bowling Alley Manager', salary: 45000, category: 'Service', requirements: { education: 'High School', smarts: 45 } },
  { id: 'job_44', title: 'Theme Park Staff', salary: 28000, category: 'Service', requirements: { education: 'None', smarts: 25 } },
  { id: 'job_45', title: 'Ride Supervisor', salary: 40000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_46', title: 'Camp Counselor', salary: 25000, category: 'Service', requirements: { education: 'High School', smarts: 35 } },
  { id: 'job_47', title: 'Hostel Manager', salary: 40000, category: 'Service', requirements: { education: 'High School', smarts: 45 } },
  { id: 'job_48', title: 'Airbnb Host', salary: 50000, category: 'Service', requirements: { education: 'None', smarts: 40 } },
  { id: 'job_49', title: 'House Flipper', salary: 60000, category: 'Service', requirements: { education: 'None', smarts: 45 } },
  { id: 'job_50', title: 'Property Manager', salary: 55000, category: 'Service', requirements: { education: 'High School', smarts: 50 } },
  { id: 'job_51', title: 'Janitor Supervisor', salary: 40000, category: 'Service', requirements: { education: 'None', smarts: 30 } },
  { id: 'job_52', title: 'Recycling Manager', salary: 45000, category: 'Service', requirements: { education: 'High School', smarts: 40 } },
  { id: 'job_53', title: 'Waste Collector', salary: 38000, category: 'Service', requirements: { education: 'None', smarts: 20 } },
  { id: 'job_54', title: 'Groundskeeper', salary: 32000, category: 'Service', requirements: { education: 'None', smarts: 25 } },
  { id: 'job_55', title: 'Gardener', salary: 30000, category: 'Service', requirements: { education: 'None', smarts: 25 } },
  { id: 'job_56', title: 'Landscaper', salary: 35000, category: 'Service', requirements: { education: 'None', smarts: 30 } },
  { id: 'job_57', title: 'Irrigation Technician', salary: 40000, category: 'Service', requirements: { education: 'None', smarts: 35 } },
  { id: 'job_58', title: 'Pest Control Manager', salary: 48000, category: 'Service', requirements: { education: 'None', smarts: 40 } },
  { id: 'job_59', title: 'Window Cleaner', salary: 30000, category: 'Service', requirements: { education: 'None', smarts: 20 } },
  { id: 'job_60', title: 'Chimney Sweep', salary: 35000, category: 'Service', requirements: { education: 'None', smarts: 25 } },

  // 🟡 TECH / MODERN JOBS — require experience to climb
  { id: 'job_61', title: 'Mobile App Developer', salary: 85000, category: 'Technology', requirements: { education: 'University', smarts: 75, minCategoryExperience: 3 } },
  { id: 'job_62', title: 'Backend Developer', salary: 95000, category: 'Technology', requirements: { education: 'University', smarts: 80, minCategoryExperience: 4 } },
  { id: 'job_63', title: 'Frontend Developer', salary: 80000, category: 'Technology', requirements: { education: 'University', smarts: 75, minCategoryExperience: 3 } },
  { id: 'job_64', title: 'DevOps Engineer', salary: 105000, category: 'Technology', requirements: { education: 'University', smarts: 85, minCategoryExperience: 6 } },
  { id: 'job_65', title: 'Cloud Architect', salary: 130000, category: 'Technology', requirements: { education: 'University', smarts: 90, minCategoryExperience: 10 } },
  { id: 'job_66', title: 'AI Researcher', salary: 120000, category: 'Technology', requirements: { education: 'University', smarts: 95, minCategoryExperience: 8 } },
  { id: 'job_67', title: 'Machine Learning Engineer', salary: 115000, category: 'Technology', requirements: { education: 'University', smarts: 90, minCategoryExperience: 7 } },
  { id: 'job_68', title: 'Game Designer', salary: 75000, category: 'Technology', requirements: { education: 'University', smarts: 75, minCategoryExperience: 3 } },
  { id: 'job_69', title: 'UI Designer', salary: 70000, category: 'Technology', requirements: { education: 'University', smarts: 70, minCategoryExperience: 2 } },
  { id: 'job_70', title: 'UX Researcher', salary: 75000, category: 'Technology', requirements: { education: 'University', smarts: 75, minCategoryExperience: 3 } },
  { id: 'job_71', title: 'Data Engineer', salary: 100000, category: 'Technology', requirements: { education: 'University', smarts: 85, minCategoryExperience: 6 } },
  { id: 'job_72', title: 'Database Engineer', salary: 90000, category: 'Technology', requirements: { education: 'University', smarts: 80, minCategoryExperience: 5 } },
  { id: 'job_73', title: 'Network Engineer', salary: 85000, category: 'Technology', requirements: { education: 'University', smarts: 80, minCategoryExperience: 4 } },
  { id: 'job_74', title: 'IT Support Specialist', salary: 45000, category: 'Technology', requirements: { education: 'High School', smarts: 60 } },
  { id: 'job_75', title: 'Systems Engineer', salary: 95000, category: 'Technology', requirements: { education: 'University', smarts: 85, minCategoryExperience: 5 } },
  { id: 'job_76', title: 'Cybersecurity Engineer', salary: 110000, category: 'Technology', requirements: { education: 'University', smarts: 90, minCategoryExperience: 7 } },
  { id: 'job_77', title: 'Ethical Hacker', salary: 105000, category: 'Technology', requirements: { education: 'University', smarts: 90, minCategoryExperience: 6 } },
  { id: 'job_78', title: 'Blockchain Developer', salary: 115000, category: 'Technology', requirements: { education: 'University', smarts: 85, minCategoryExperience: 5 } },
  { id: 'job_79', title: 'Web Designer', salary: 60000, category: 'Technology', requirements: { education: 'University', smarts: 65, minCategoryExperience: 2 } },
  { id: 'job_80', title: 'Digital Artist', salary: 55000, category: 'Media', requirements: { education: 'University', smarts: 65, minCategoryExperience: 2 } },
  { id: 'job_81', title: 'Animator', salary: 65000, category: 'Media', requirements: { education: 'University', smarts: 70, minCategoryExperience: 3 } },
  { id: 'job_82', title: 'VFX Artist', salary: 75000, category: 'Media', requirements: { education: 'University', smarts: 75, minCategoryExperience: 5 } },
  { id: 'job_83', title: 'Video Editor', salary: 50000, category: 'Media', requirements: { education: 'University', smarts: 60, minCategoryExperience: 2 } },
  { id: 'job_84', title: 'Sound Engineer', salary: 60000, category: 'Media', requirements: { education: 'University', smarts: 70, minCategoryExperience: 3 } },
  { id: 'job_85', title: 'Music Producer', salary: 70000, category: 'Media', requirements: { education: 'University', smarts: 75, minCategoryExperience: 5 } },
  { id: 'job_86', title: 'Podcast Producer', salary: 55000, category: 'Media', requirements: { education: 'University', smarts: 65, minCategoryExperience: 3 } },
  { id: 'job_87', title: 'Content Strategist', salary: 75000, category: 'Corporate', requirements: { education: 'University', smarts: 75, minCategoryExperience: 4 } },
  { id: 'job_88', title: 'SEO Specialist', salary: 60000, category: 'Corporate', requirements: { education: 'University', smarts: 70, minCategoryExperience: 3 } },
  { id: 'job_89', title: 'Ads Manager', salary: 65000, category: 'Corporate', requirements: { education: 'University', smarts: 75, minCategoryExperience: 4 } },
  { id: 'job_90', title: 'Social Media Strategist', salary: 55000, category: 'Corporate', requirements: { education: 'University', smarts: 70, minCategoryExperience: 3 } },
  { id: 'job_91', title: 'Influencer Manager', salary: 60000, category: 'Corporate', requirements: { education: 'University', smarts: 70, minCategoryExperience: 3 } },
  { id: 'job_92', title: 'Brand Manager', salary: 85000, category: 'Corporate', requirements: { education: 'University', smarts: 80, minCategoryExperience: 6 } },
  { id: 'job_93', title: 'Product Manager', salary: 100000, category: 'Corporate', requirements: { education: 'University', smarts: 85, minCategoryExperience: 8 } },
  { id: 'job_94', title: 'Startup Founder', salary: 60000, category: 'Corporate', requirements: { education: 'None', smarts: 85, minTotalExperience: 5 } },
  { id: 'job_95', title: 'Tech Consultant', salary: 95000, category: 'Technology', requirements: { education: 'University', smarts: 85, minCategoryExperience: 7 } },
  { id: 'job_96', title: 'Data Analyst', salary: 70000, category: 'Technology', requirements: { education: 'University', smarts: 75, minCategoryExperience: 2 } },
  { id: 'job_97', title: 'Business Analyst', salary: 75000, category: 'Corporate', requirements: { education: 'University', smarts: 80, minCategoryExperience: 3 } },
  { id: 'job_98', title: 'QA Tester', salary: 48000, category: 'Technology', requirements: { education: 'High School', smarts: 60 } },
  { id: 'job_99', title: 'Game Tester', salary: 38000, category: 'Technology', requirements: { education: 'None', smarts: 50 } },
  { id: 'job_100', title: 'Indie Developer', salary: 45000, category: 'Technology', requirements: { education: 'None', smarts: 75, minCategoryExperience: 2 } },
  { id: 'job_101', title: 'Robotics Engineer', salary: 105000, category: 'Technology', requirements: { education: 'University', smarts: 90, minCategoryExperience: 7 } },
  { id: 'job_102', title: 'AI Ethics Specialist', salary: 90000, category: 'Technology', requirements: { education: 'University', smarts: 85, minCategoryExperience: 5 } },
  { id: 'job_103', title: 'VR Developer', salary: 95000, category: 'Technology', requirements: { education: 'University', smarts: 85, minCategoryExperience: 5 } },
  { id: 'job_104', title: 'AR Designer', salary: 85000, category: 'Technology', requirements: { education: 'University', smarts: 80, minCategoryExperience: 4 } },
  { id: 'job_105', title: 'Quantum Computing Researcher', salary: 140000, category: 'Technology', requirements: { education: 'University', smarts: 98, minCategoryExperience: 12 } },
  { id: 'job_106', title: 'IoT Solutions Architect', salary: 120000, category: 'Technology', requirements: { education: 'University', smarts: 90, minCategoryExperience: 10 } },
  { id: 'job_107', title: 'Smart City Planner', salary: 100000, category: 'Technology', requirements: { education: 'University', smarts: 85, minCategoryExperience: 8 } },
  { id: 'job_108', title: 'Drone Pilot', salary: 55000, category: 'Technology', requirements: { education: 'High School', smarts: 65, minCategoryExperience: 1 } },
  { id: 'job_109', title: '3D Printing Specialist', salary: 60000, category: 'Technology', requirements: { education: 'High School', smarts: 70, minCategoryExperience: 2 } },
  { id: 'job_110', title: 'Bioinformatics Analyst', salary: 85000, category: 'Technology', requirements: { education: 'University', smarts: 85, minCategoryExperience: 5 } },

  // 🔵 MEDICAL / LAW / ELITE — long education + experience paths
  { id: 'job_111', title: 'General Doctor', salary: 100000, category: 'Health', requirements: { education: 'Medical School', smarts: 90, minCategoryExperience: 4 } },
  { id: 'job_112', title: 'Surgeon', salary: 180000, category: 'Health', requirements: { education: 'Medical School', smarts: 95, minCategoryExperience: 12 } },
  { id: 'job_113', title: 'Cardiologist', salary: 200000, category: 'Health', requirements: { education: 'Medical School', smarts: 95, minCategoryExperience: 15 } },
  { id: 'job_114', title: 'Neurologist', salary: 190000, category: 'Health', requirements: { education: 'Medical School', smarts: 95, minCategoryExperience: 14 } },
  { id: 'job_115', title: 'Psychiatrist', salary: 130000, category: 'Health', requirements: { education: 'Medical School', smarts: 90, minCategoryExperience: 8 } },
  { id: 'job_116', title: 'Dentist', salary: 95000, category: 'Health', requirements: { education: 'Dental School', smarts: 85, minCategoryExperience: 4 } },
  { id: 'job_117', title: 'Pharmacist', salary: 80000, category: 'Health', requirements: { education: 'Pharmacy School', smarts: 85, minCategoryExperience: 3 } },
  { id: 'job_118', title: 'Nurse', salary: 50000, category: 'Health', requirements: { education: 'Nursing School', smarts: 75 } },
  { id: 'job_119', title: 'Paramedic', salary: 38000, category: 'Health', requirements: { education: 'High School', smarts: 70 } },
  { id: 'job_120', title: 'Medical Researcher', salary: 75000, category: 'Health', requirements: { education: 'PhD Program', smarts: 95, minCategoryExperience: 5 } },
  { id: 'job_121', title: 'Lawyer', salary: 65000, category: 'Law', requirements: { education: 'Law School', smarts: 90, minCategoryExperience: 2 } },
  { id: 'job_122', title: 'Criminal Lawyer', salary: 80000, category: 'Law', requirements: { education: 'Law School', smarts: 90, minCategoryExperience: 5 } },
  { id: 'job_123', title: 'Corporate Lawyer', salary: 100000, category: 'Law', requirements: { education: 'Law School', smarts: 95, minCategoryExperience: 8 } },
  { id: 'job_124', title: 'Judge', salary: 130000, category: 'Law', requirements: { education: 'Law School', smarts: 95, minCategoryExperience: 15 } },
  { id: 'job_125', title: 'Prosecutor', salary: 75000, category: 'Law', requirements: { education: 'Law School', smarts: 90, minCategoryExperience: 5 } },
  { id: 'job_126', title: 'Notary', salary: 42000, category: 'Law', requirements: { education: 'High School', smarts: 70, minCategoryExperience: 2 } },
  { id: 'job_127', title: 'Legal Advisor', salary: 65000, category: 'Law', requirements: { education: 'Law School', smarts: 85, minCategoryExperience: 4 } },
  { id: 'job_128', title: 'Paralegal', salary: 38000, category: 'Law', requirements: { education: 'High School', smarts: 75 } },
  { id: 'job_129', title: 'Immigration Lawyer', salary: 75000, category: 'Law', requirements: { education: 'Law School', smarts: 90, minCategoryExperience: 5 } },
  { id: 'job_130', title: 'Patent Lawyer', salary: 95000, category: 'Law', requirements: { education: 'Law School', smarts: 95, minCategoryExperience: 8 } },
  { id: 'job_131', title: 'Airline Pilot', salary: 85000, category: 'Aviation', requirements: { education: 'University', smarts: 85, minCategoryExperience: 5 } },
  { id: 'job_132', title: 'Helicopter Pilot', salary: 55000, category: 'Aviation', requirements: { education: 'High School', smarts: 80, minCategoryExperience: 3 } },
  { id: 'job_133', title: 'Air Traffic Controller', salary: 70000, category: 'Aviation', requirements: { education: 'High School', smarts: 85, minCategoryExperience: 4 } },
  { id: 'job_134', title: 'Ship Captain', salary: 65000, category: 'Aviation', requirements: { education: 'University', smarts: 80, minCategoryExperience: 6 } },
  { id: 'job_135', title: 'Logistics Director', salary: 80000, category: 'Corporate', requirements: { education: 'University', smarts: 85, minCategoryExperience: 8 } },
  { id: 'job_136', title: 'Pediatrician', salary: 110000, category: 'Health', requirements: { education: 'Medical School', smarts: 90, minCategoryExperience: 6 } },
  { id: 'job_137', title: 'Oncologist', salary: 180000, category: 'Health', requirements: { education: 'Medical School', smarts: 95, minCategoryExperience: 14 } },
  { id: 'job_138', title: 'Dermatologist', salary: 150000, category: 'Health', requirements: { education: 'Medical School', smarts: 95, minCategoryExperience: 10 } },
  { id: 'job_139', title: 'Anesthesiologist', salary: 200000, category: 'Health', requirements: { education: 'Medical School', smarts: 95, minCategoryExperience: 12 } },
  { id: 'job_140', title: 'Orthodontist', salary: 120000, category: 'Health', requirements: { education: 'Dental School', smarts: 90, minCategoryExperience: 8 } },
  { id: 'job_141', title: 'Veterinarian', salary: 60000, category: 'Health', requirements: { education: 'Veterinary School', smarts: 85, minCategoryExperience: 3 } },
  { id: 'job_142', title: 'Physical Therapist', salary: 55000, category: 'Health', requirements: { education: 'University', smarts: 80, minCategoryExperience: 2 } },
  { id: 'job_143', title: 'Optometrist', salary: 65000, category: 'Health', requirements: { education: 'University', smarts: 85, minCategoryExperience: 4 } },
  { id: 'job_144', title: 'Chiropractor', salary: 55000, category: 'Health', requirements: { education: 'University', smarts: 80, minCategoryExperience: 3 } },
  { id: 'job_145', title: 'Chief Medical Officer', salary: 220000, category: 'Health', requirements: { education: 'Medical School', smarts: 98, minCategoryExperience: 20 } },

  // 🔴 EXECUTIVE / HIGH LEVEL — require extensive career experience
  { id: 'job_146', title: 'CEO', salary: 200000, category: 'Corporate', requirements: { education: 'Business School', smarts: 95, minTotalExperience: 20 } },
  { id: 'job_147', title: 'CFO', salary: 170000, category: 'Corporate', requirements: { education: 'Business School', smarts: 95, minCategoryExperience: 15 } },
  { id: 'job_148', title: 'CTO', salary: 170000, category: 'Technology', requirements: { education: 'Business School', smarts: 95, minCategoryExperience: 15 } },
  { id: 'job_149', title: 'COO', salary: 155000, category: 'Corporate', requirements: { education: 'Business School', smarts: 90, minTotalExperience: 15 } },
  { id: 'job_150', title: 'Venture Capitalist', salary: 200000, category: 'Finance', requirements: { education: 'Business School', smarts: 95, minCategoryExperience: 15 } },
  { id: 'job_151', title: 'Hedge Fund Manager', salary: 300000, category: 'Finance', requirements: { education: 'Business School', smarts: 98, minCategoryExperience: 20 } },
  { id: 'job_152', title: 'Investment Banker', salary: 120000, category: 'Finance', requirements: { education: 'Business School', smarts: 90, minCategoryExperience: 5 } },
  { id: 'job_153', title: 'Private Equity Manager', salary: 180000, category: 'Finance', requirements: { education: 'Business School', smarts: 95, minCategoryExperience: 12 } },
  { id: 'job_154', title: 'Real Estate Mogul', salary: 200000, category: 'Finance', requirements: { education: 'None', smarts: 85, minTotalExperience: 20 } },
  { id: 'job_155', title: 'Franchise Owner', salary: 90000, category: 'Corporate', requirements: { education: 'None', smarts: 80, minTotalExperience: 10 } },
  { id: 'job_156', title: 'Chief Marketing Officer', salary: 140000, category: 'Corporate', requirements: { education: 'Business School', smarts: 90, minCategoryExperience: 12 } },
  { id: 'job_157', title: 'Chief Information Officer', salary: 150000, category: 'Technology', requirements: { education: 'Business School', smarts: 90, minCategoryExperience: 14 } },
  { id: 'job_158', title: 'Chief Data Officer', salary: 145000, category: 'Technology', requirements: { education: 'Business School', smarts: 95, minCategoryExperience: 12 } },
  { id: 'job_159', title: 'Chief Security Officer', salary: 135000, category: 'Technology', requirements: { education: 'Business School', smarts: 90, minCategoryExperience: 12 } },
  { id: 'job_160', title: 'Managing Director', salary: 160000, category: 'Corporate', requirements: { education: 'Business School', smarts: 95, minTotalExperience: 18 } },
  { id: 'job_161', title: 'Board Member', salary: 80000, category: 'Corporate', requirements: { education: 'Business School', smarts: 90, minTotalExperience: 15 } },
  { id: 'job_162', title: 'Global Sales Director', salary: 120000, category: 'Corporate', requirements: { education: 'Business School', smarts: 85, minCategoryExperience: 10 } },
  { id: 'job_163', title: 'VP of Engineering', salary: 140000, category: 'Technology', requirements: { education: 'Business School', smarts: 90, minCategoryExperience: 12 } },
  { id: 'job_164', title: 'VP of Product', salary: 130000, category: 'Corporate', requirements: { education: 'Business School', smarts: 90, minCategoryExperience: 10 } },
  { id: 'job_165', title: 'VP of Design', salary: 120000, category: 'Corporate', requirements: { education: 'Business School', smarts: 85, minCategoryExperience: 10 } },

  // 🟣 UNIQUE / FUN JOBS — reduced pay, require experience or popularity
  { id: 'job_166', title: 'YouTuber', salary: 60000, category: 'Media', requirements: { education: 'None', smarts: 50, popularity: 30, minCategoryExperience: 2 } },
  { id: 'job_167', title: 'Streamer', salary: 50000, category: 'Media', requirements: { education: 'None', smarts: 50, popularity: 25 } },
  { id: 'job_168', title: 'Influencer', salary: 45000, category: 'Media', requirements: { education: 'None', smarts: 50, popularity: 40 } },
  { id: 'job_169', title: 'Esports Player', salary: 60000, category: 'Media', requirements: { education: 'None', smarts: 60, minCategoryExperience: 3 } },
  { id: 'job_170', title: 'Professional Gamer', salary: 50000, category: 'Media', requirements: { education: 'None', smarts: 60, minCategoryExperience: 2 } },
  { id: 'job_171', title: 'Casino High Roller', salary: 150000, category: 'Finance', requirements: { education: 'None', smarts: 80, minTotalExperience: 15, money: 500000 } },
  { id: 'job_172', title: 'Poker Player', salary: 80000, category: 'Finance', requirements: { education: 'None', smarts: 85, minTotalExperience: 8 } },
  { id: 'job_173', title: 'Day Trader', salary: 90000, category: 'Finance', requirements: { education: 'None', smarts: 85, minCategoryExperience: 5 } },
  { id: 'job_174', title: 'Crypto Trader', salary: 70000, category: 'Finance', requirements: { education: 'None', smarts: 80, minCategoryExperience: 3 } },
  { id: 'job_175', title: 'NFT Artist', salary: 40000, category: 'Media', requirements: { education: 'None', smarts: 60, minCategoryExperience: 2 } },
  { id: 'job_176', title: 'Explorer', salary: 50000, category: 'Science', requirements: { education: 'None', smarts: 70, minTotalExperience: 5 } },
  { id: 'job_177', title: 'Spy', salary: 90000, category: 'Politics', requirements: { education: 'None', smarts: 90, minTotalExperience: 10 } },
  { id: 'job_178', title: 'Hacker', salary: 80000, category: 'Technology', requirements: { education: 'None', smarts: 95, minCategoryExperience: 5 } },
  { id: 'job_179', title: 'Bounty Hunter', salary: 65000, category: 'Law', requirements: { education: 'None', smarts: 70, minTotalExperience: 5 } },
  { id: 'job_180', title: 'Private Investigator', salary: 55000, category: 'Law', requirements: { education: 'None', smarts: 80, minTotalExperience: 5 } },
  { id: 'job_181', title: 'Astronaut', salary: 120000, category: 'Science', requirements: { education: 'University', smarts: 95, minTotalExperience: 15 } },
  { id: 'job_182', title: 'Stunt Double', salary: 55000, category: 'Media', requirements: { education: 'None', smarts: 50, health: 60 } },
  { id: 'job_183', title: 'Voice Actor', salary: 50000, category: 'Media', requirements: { education: 'None', smarts: 60, minCategoryExperience: 2 } },
  { id: 'job_184', title: 'Magician', salary: 45000, category: 'Media', requirements: { education: 'None', smarts: 60, minCategoryExperience: 3 } },
  { id: 'job_185', title: 'Comedian', salary: 55000, category: 'Media', requirements: { education: 'None', smarts: 70, popularity: 20, minCategoryExperience: 3 } },
  { id: 'job_186', title: 'AI Engineer', salary: 125000, category: 'Technology', requirements: { education: 'University', smarts: 92, minCategoryExperience: 4 } },
  { id: 'job_187', title: 'Cybersecurity Analyst', salary: 85000, category: 'Technology', requirements: { education: 'University', smarts: 82, minCategoryExperience: 2 } },
  { id: 'job_188', title: 'Cloud Security Architect', salary: 145000, category: 'Technology', requirements: { education: 'University', smarts: 95, minCategoryExperience: 10 } },
  { id: 'job_189', title: 'Robotics Technician', salary: 65000, category: 'Engineering', requirements: { education: 'Trade School', alternativeEducation: 'High School', smarts: 70, minCategoryExperience: 1 } },
  { id: 'job_190', title: 'Civil Engineer', salary: 90000, category: 'Engineering', requirements: { education: 'University', smarts: 80, minCategoryExperience: 3 } },
  { id: 'job_191', title: 'Mechanical Engineer', salary: 95000, category: 'Engineering', requirements: { education: 'University', smarts: 82, minCategoryExperience: 4 } },
  { id: 'job_192', title: 'Electrical Engineer', salary: 98000, category: 'Engineering', requirements: { education: 'University', smarts: 85, minCategoryExperience: 5 } },
  { id: 'job_193', title: 'Renewable Energy Engineer', salary: 110000, category: 'Engineering', requirements: { education: 'University', smarts: 88, minCategoryExperience: 6 } },
  { id: 'job_194', title: 'Data Privacy Officer', salary: 115000, category: 'Corporate', requirements: { education: 'University', smarts: 90, minCategoryExperience: 6 } },
  { id: 'job_195', title: 'Financial Planner', salary: 65000, category: 'Finance', requirements: { education: 'Business School', alternativeEducation: 'University', smarts: 75, minCategoryExperience: 2 } },
  { id: 'job_196', title: 'Actuary', salary: 120000, category: 'Finance', requirements: { education: 'University', smarts: 92, minCategoryExperience: 5 } },
  { id: 'job_197', title: 'Risk Manager', salary: 110000, category: 'Finance', requirements: { education: 'Business School', smarts: 90, minCategoryExperience: 6 } },
  { id: 'job_198', title: 'Nurse Practitioner', salary: 105000, category: 'Health', requirements: { education: 'Nursing School', smarts: 85, minCategoryExperience: 5 } },
  { id: 'job_199', title: 'Radiology Technologist', salary: 70000, category: 'Health', requirements: { education: 'Trade School', alternativeEducation: 'Nursing School', smarts: 78, minCategoryExperience: 2 } },
  { id: 'job_200', title: 'Genetic Counselor', salary: 115000, category: 'Health', requirements: { education: 'Graduate School', smarts: 90, minCategoryExperience: 6 } },
  { id: 'job_201', title: 'Elementary Teacher', salary: 45000, category: 'Education', requirements: { education: 'University', smarts: 70, minCategoryExperience: 1 } },
  { id: 'job_202', title: 'Curriculum Developer', salary: 70000, category: 'Education', requirements: { education: 'Graduate School', smarts: 80, minCategoryExperience: 3 } },
  { id: 'job_203', title: 'School Principal', salary: 95000, category: 'Education', requirements: { education: 'Graduate School', smarts: 88, minCategoryExperience: 8 } },
  { id: 'job_204', title: 'University Professor', salary: 140000, category: 'Education', requirements: { education: 'PhD Program', smarts: 95, minCategoryExperience: 12 } },
  { id: 'job_205', title: 'Esports Coach', salary: 85000, category: 'Entertainment', requirements: { education: 'None', smarts: 75, popularity: 20, minCategoryExperience: 3 } },
  { id: 'job_206', title: 'Streaming Producer', salary: 75000, category: 'Media', requirements: { education: 'University', smarts: 70, minCategoryExperience: 3 } },
  { id: 'job_207', title: 'Talent Scout', salary: 60000, category: 'Entertainment', requirements: { education: 'High School', smarts: 65, popularity: 15, minCategoryExperience: 2 } },
  { id: 'job_208', title: 'Supply Chain Analyst', salary: 78000, category: 'Corporate', requirements: { education: 'University', smarts: 75, minCategoryExperience: 2 } },
  { id: 'job_209', title: 'Freight Broker', salary: 90000, category: 'Corporate', requirements: { education: 'High School', smarts: 70, minCategoryExperience: 2 } },
  { id: 'job_210', title: 'Port Operations Manager', salary: 110000, category: 'Maritime', requirements: { education: 'Maritime Academy', smarts: 85, minCategoryExperience: 6 } },
  { id: 'job_211', title: 'Warehouse Automation Engineer', salary: 115000, category: 'Technology', requirements: { education: 'University', smarts: 88, minCategoryExperience: 5 } },
  { id: 'job_212', title: 'Diplomatic Attaché', salary: 100000, category: 'Politics', requirements: { education: 'Diplomatic Academy', smarts: 90, minCategoryExperience: 8 } },
  { id: 'job_213', title: 'Public Defender', salary: 85000, category: 'Law', requirements: { education: 'Law School', smarts: 88, minCategoryExperience: 4 } },
  { id: 'job_214', title: 'Compliance Officer', salary: 95000, category: 'Finance', requirements: { education: 'University', smarts: 85, minCategoryExperience: 5 } },
  { id: 'job_215', title: 'Sustainability Consultant', salary: 90000, category: 'Science', requirements: { education: 'University', smarts: 82, minCategoryExperience: 4 } },
  { id: 'job_216', title: 'Forensic Scientist', salary: 95000, category: 'Science', requirements: { education: 'University', smarts: 90, minCategoryExperience: 5 } },
  { id: 'job_217', title: 'Space Systems Engineer', salary: 150000, category: 'Science', requirements: { education: 'Space Training', alternativeEducation: 'University', smarts: 96, minCategoryExperience: 10 } },
  { id: 'job_218', title: 'Sports Psychologist', salary: 95000, category: 'Health', requirements: { education: 'Counseling School', smarts: 85, minCategoryExperience: 4 } },
  { id: 'job_219', title: 'Museum Curator', salary: 55000, category: 'Media', requirements: { education: 'University', smarts: 65, minCategoryExperience: 2 } },
  { id: 'job_220', title: 'Airline Operations Manager', salary: 105000, category: 'Aviation', requirements: { education: 'Flight School', alternativeEducation: 'University', smarts: 82, minCategoryExperience: 6 } },
  { id: 'job_221', title: 'E-commerce Operations Manager', salary: 85000, category: 'Corporate', requirements: { education: 'University', smarts: 78, minCategoryExperience: 3 } },
  { id: 'job_222', title: 'Social Media Platform Product Lead', salary: 135000, category: 'Corporate', requirements: { education: 'Business School', smarts: 92, minCategoryExperience: 10 } },
  { id: 'job_223', title: 'Streaming Service Executive', salary: 160000, category: 'Media', requirements: { education: 'Business School', smarts: 94, minCategoryExperience: 12 } },
  { id: 'job_224', title: 'Automotive Design Engineer', salary: 130000, category: 'Engineering', requirements: { education: 'University', smarts: 90, minCategoryExperience: 8 } },
  { id: 'job_225', title: 'Marine Biologist', salary: 80000, category: 'Science', requirements: { education: 'University', smarts: 85, minCategoryExperience: 4 } },
  { id: 'job_226', title: 'Clinical Psychologist', salary: 120000, category: 'Health', requirements: { education: 'Counseling School', smarts: 90, minCategoryExperience: 6 } },
  { id: 'job_227', title: 'School District Superintendent', salary: 160000, category: 'Education', requirements: { education: 'PhD Program', smarts: 95, minCategoryExperience: 15 } },
  { id: 'job_228', title: 'Sports Agent', salary: 95000, category: 'Entertainment', requirements: { education: 'University', smarts: 80, popularity: 20, minCategoryExperience: 5 } },
  
  // Politics
  { id: 'pol_1', title: 'School Board Member', salary: 15000, category: 'Politics', requirements: { education: 'High School', smarts: 50, age: 21, popularity: 10, money: 1000 } },
  { id: 'pol_2', title: 'City Council Member', salary: 45000, category: 'Politics', requirements: { previousJobId: 'pol_1', yearsInPreviousJob: 3, smarts: 60, age: 25, popularity: 25, money: 5000 } },
  { id: 'pol_3', title: 'Mayor', salary: 100000, category: 'Politics', requirements: { previousJobId: 'pol_2', yearsInPreviousJob: 5, smarts: 70, age: 30, popularity: 40, money: 50000 } },
  { id: 'pol_4', title: 'State Representative', salary: 75000, category: 'Politics', requirements: { previousJobId: 'pol_3', yearsInPreviousJob: 5, smarts: 75, age: 35, popularity: 50, money: 100000 } },
  { id: 'pol_5', title: 'State Senator', salary: 85000, category: 'Politics', requirements: { previousJobId: 'pol_4', yearsInPreviousJob: 5, smarts: 80, age: 35, popularity: 60, money: 250000 } },
  { id: 'pol_6', title: 'Governor', salary: 160000, category: 'Politics', requirements: { previousJobId: 'pol_5', yearsInPreviousJob: 5, smarts: 85, age: 40, popularity: 75, money: 1000000 } },
  { id: 'pol_7', title: 'President', salary: 400000, category: 'Politics', requirements: { previousJobId: 'pol_6', yearsInPreviousJob: 5, smarts: 90, age: 40, popularity: 90, money: 10000000 } }
];
