import { BusinessDefinition, BusinessUpgrade } from './types';

export const CORE_UPGRADES: Omit<BusinessUpgrade, 'purchased' | 'isCore'>[] = [
  { id: 'core_1', name: 'Basic Improvements', costMultiplier: 0.2, profitBoost: 0.05 },
  { id: 'core_2', name: 'Equipment Upgrade', costMultiplier: 0.3, profitBoost: 0.08 },
  { id: 'core_3', name: 'Staff Expansion', costMultiplier: 0.4, profitBoost: 0.12 },
  { id: 'core_4', name: 'Marketing Boost', costMultiplier: 0.5, profitBoost: 0.15 },
  { id: 'core_5', name: 'Automation', costMultiplier: 0.75, profitBoost: 0.20 },
  { id: 'core_6', name: 'Premium Expansion', costMultiplier: 1.0, profitBoost: 0.30 },
];

const smallBusinesses = [
  { name: 'Lemonade Stand', price: 2000, risk: 'Low', upgrades: [
    { id: 'u1', name: 'Better lemons', costMultiplier: 0.1, profitBoost: 0.02 },
    { id: 'u2', name: 'Bigger stand', costMultiplier: 0.15, profitBoost: 0.03 },
    { id: 'u3', name: 'Add flavors', costMultiplier: 0.2, profitBoost: 0.05 },
    { id: 'u4', name: 'Hire helper', costMultiplier: 0.25, profitBoost: 0.08 },
  ]},
  { name: 'Lawn Care Service', price: 5000, risk: 'Low', upgrades: [
    { id: 'u1', name: 'Buy mower', costMultiplier: 0.1, profitBoost: 0.02 },
    { id: 'u2', name: 'Hire workers', costMultiplier: 0.2, profitBoost: 0.05 },
    { id: 'u3', name: 'Add landscaping', costMultiplier: 0.3, profitBoost: 0.08 },
    { id: 'u4', name: 'Contracts', costMultiplier: 0.4, profitBoost: 0.1 },
  ]},
  { name: 'Car Wash (manual)', price: 25000, risk: 'Low', upgrades: [
    { id: 'u1', name: 'Automatic system', costMultiplier: 0.3, profitBoost: 0.08 },
    { id: 'u2', name: 'Premium wash', costMultiplier: 0.2, profitBoost: 0.05 },
    { id: 'u3', name: 'Memberships', costMultiplier: 0.4, profitBoost: 0.1 },
    { id: 'u4', name: 'Expand lanes', costMultiplier: 0.5, profitBoost: 0.12 },
  ]},
  { name: 'Food Truck', price: 75000, risk: 'Medium', upgrades: [
    { id: 'u1', name: 'New recipes', costMultiplier: 0.15, profitBoost: 0.04 },
    { id: 'u2', name: 'Better location', costMultiplier: 0.25, profitBoost: 0.06 },
    { id: 'u3', name: 'Branding', costMultiplier: 0.3, profitBoost: 0.08 },
    { id: 'u4', name: 'Multiple trucks', costMultiplier: 0.8, profitBoost: 0.2 },
  ]},
  { name: 'Coffee Cart', price: 40000, risk: 'Low', upgrades: [
    { id: 'u1', name: 'Premium beans', costMultiplier: 0.1, profitBoost: 0.03 },
    { id: 'u2', name: 'Add pastries', costMultiplier: 0.15, profitBoost: 0.04 },
    { id: 'u3', name: 'Morning rush boost', costMultiplier: 0.2, profitBoost: 0.06 },
    { id: 'u4', name: 'Expand to café', costMultiplier: 1.0, profitBoost: 0.25 },
  ]},
  { name: 'Ice Cream Stand', price: 30000, risk: 'Low', upgrades: [] },
  { name: 'Phone Repair Shop', price: 60000, risk: 'Medium', upgrades: [] },
  { name: 'Cleaning Service', price: 10000, risk: 'Low', upgrades: [] },
  { name: 'Pet Walking Business', price: 3000, risk: 'Low', upgrades: [] },
  { name: 'Small Bakery', price: 120000, risk: 'Medium', upgrades: [] },
  // 50 more small businesses
  { name: 'Dog grooming', price: 15000, risk: 'Low', upgrades: [] },
  { name: 'Car detailing', price: 10000, risk: 'Low', upgrades: [] },
  { name: 'Tutoring service', price: 2000, risk: 'Low', upgrades: [] },
  { name: 'Babysitting agency', price: 5000, risk: 'Low', upgrades: [] },
  { name: 'Handyman service', price: 8000, risk: 'Low', upgrades: [] },
  { name: 'Window cleaning', price: 4000, risk: 'Low', upgrades: [] },
  { name: 'Mobile car repair', price: 25000, risk: 'Medium', upgrades: [] },
  { name: 'Bike repair shop', price: 15000, risk: 'Low', upgrades: [] },
  { name: 'Flower shop', price: 30000, risk: 'Low', upgrades: [] },
  { name: 'Street food stand', price: 12000, risk: 'Low', upgrades: [] },
  { name: 'Juice bar', price: 25000, risk: 'Low', upgrades: [] },
  { name: 'Smoothie stand', price: 20000, risk: 'Low', upgrades: [] },
  { name: 'Toy store', price: 40000, risk: 'Medium', upgrades: [] },
  { name: 'Thrift shop', price: 15000, risk: 'Low', upgrades: [] },
  { name: 'Art shop', price: 20000, risk: 'Low', upgrades: [] },
  { name: 'Gaming café', price: 50000, risk: 'Medium', upgrades: [] },
  { name: 'Laundry service', price: 35000, risk: 'Low', upgrades: [] },
  { name: 'Nail salon', price: 40000, risk: 'Low', upgrades: [] },
  { name: 'Tattoo shop', price: 30000, risk: 'Medium', upgrades: [] },
  { name: 'Photography studio', price: 25000, risk: 'Low', upgrades: [] },
  { name: 'Mobile pet vet', price: 60000, risk: 'Medium', upgrades: [] },
  { name: 'Car rental (small)', price: 100000, risk: 'Medium', upgrades: [] },
  { name: 'Drone photography', price: 12000, risk: 'Low', upgrades: [] },
  { name: 'Phone accessories shop', price: 20000, risk: 'Low', upgrades: [] },
  { name: 'Local delivery service', price: 15000, risk: 'Low', upgrades: [] },
  { name: 'Vending machines', price: 20000, risk: 'Low', upgrades: [] },
  { name: 'Popcorn stand', price: 5000, risk: 'Low', upgrades: [] },
  { name: 'Shoe cleaning', price: 3000, risk: 'Low', upgrades: [] },
  { name: 'Mini golf', price: 80000, risk: 'Medium', upgrades: [] },
  { name: 'Arcade', price: 150000, risk: 'Medium', upgrades: [] },
  { name: 'Ice rink', price: 200000, risk: 'High', upgrades: [] },
  { name: 'Candy store', price: 30000, risk: 'Low', upgrades: [] },
  { name: 'Board game café', price: 45000, risk: 'Medium', upgrades: [] },
  { name: 'Fishing shop', price: 35000, risk: 'Low', upgrades: [] },
  { name: 'Camping gear shop', price: 50000, risk: 'Medium', upgrades: [] },
  { name: 'Music lessons', price: 5000, risk: 'Low', upgrades: [] },
  { name: 'Dance studio', price: 60000, risk: 'Medium', upgrades: [] },
  { name: 'Language school', price: 40000, risk: 'Medium', upgrades: [] },
  { name: 'Printing shop', price: 80000, risk: 'Medium', upgrades: [] },
  { name: 'Courier service', price: 25000, risk: 'Low', upgrades: [] },
  { name: 'Car wrapping', price: 30000, risk: 'Medium', upgrades: [] },
  { name: 'Barbecue stand', price: 15000, risk: 'Low', upgrades: [] },
  { name: 'Hot dog stand', price: 8000, risk: 'Low', upgrades: [] },
  { name: 'Pop-up shop', price: 10000, risk: 'Low', upgrades: [] },
  { name: 'Second-hand electronics', price: 20000, risk: 'Medium', upgrades: [] },
  { name: 'Watch repair', price: 15000, risk: 'Low', upgrades: [] },
  { name: 'Jewelry stand', price: 25000, risk: 'Medium', upgrades: [] },
  { name: 'Farm stand', price: 5000, risk: 'Low', upgrades: [] },
  { name: 'Parking lot business', price: 100000, risk: 'Low', upgrades: [] }
];

const mediumBusinesses = [
  { name: 'Restaurant (small)', price: 300000, risk: 'Medium', upgrades: [
    { id: 'u1', name: 'Better chef', costMultiplier: 0.2, profitBoost: 0.05 },
    { id: 'u2', name: 'Interior design', costMultiplier: 0.3, profitBoost: 0.08 },
    { id: 'u3', name: 'Delivery service', costMultiplier: 0.4, profitBoost: 0.1 },
    { id: 'u4', name: 'Franchise', costMultiplier: 1.5, profitBoost: 0.4 },
  ]},
  { name: 'Café', price: 150000, risk: 'Medium', upgrades: [] },
  { name: 'Clothing Store', price: 200000, risk: 'Medium', upgrades: [
    { id: 'u1', name: 'Trendy items', costMultiplier: 0.2, profitBoost: 0.05 },
    { id: 'u2', name: 'Online store', costMultiplier: 0.3, profitBoost: 0.08 },
    { id: 'u3', name: 'Brand deals', costMultiplier: 0.5, profitBoost: 0.12 },
    { id: 'u4', name: 'Seasonal sales', costMultiplier: 0.4, profitBoost: 0.1 },
  ]},
  { name: 'Gym', price: 250000, risk: 'Medium', upgrades: [
    { id: 'u1', name: 'New equipment', costMultiplier: 0.2, profitBoost: 0.05 },
    { id: 'u2', name: 'Personal trainers', costMultiplier: 0.3, profitBoost: 0.08 },
    { id: 'u3', name: 'VIP membership', costMultiplier: 0.4, profitBoost: 0.1 },
    { id: 'u4', name: 'Expand space', costMultiplier: 0.8, profitBoost: 0.2 },
  ]},
  { name: 'Barbershop', price: 80000, risk: 'Low', upgrades: [] },
  { name: 'Car Dealership', price: 500000, risk: 'High', upgrades: [] },
  { name: 'Convenience Store', price: 120000, risk: 'Low', upgrades: [] },
  { name: 'Bookstore', price: 100000, risk: 'Medium', upgrades: [] },
  { name: 'Electronics Store', price: 400000, risk: 'High', upgrades: [] },
  { name: 'Pharmacy', price: 500000, risk: 'Medium', upgrades: [] },
  // 70 more medium businesses
  { name: 'Supermarket', price: 1500000, risk: 'Medium', upgrades: [] },
  { name: 'Furniture store', price: 800000, risk: 'Medium', upgrades: [] },
  { name: 'Gym chain', price: 2000000, risk: 'Medium', upgrades: [] },
  { name: 'Restaurant chain', price: 3000000, risk: 'High', upgrades: [] },
  { name: 'Car rental company', price: 1500000, risk: 'Medium', upgrades: [] },
  { name: 'Driving school', price: 250000, risk: 'Low', upgrades: [] },
  { name: 'Pet hotel', price: 400000, risk: 'Medium', upgrades: [] },
  { name: 'Daycare center', price: 350000, risk: 'Medium', upgrades: [] },
  { name: 'Cinema', price: 2500000, risk: 'High', upgrades: [] },
  { name: 'Bowling alley', price: 1200000, risk: 'Medium', upgrades: [] },
  { name: 'Escape room', price: 300000, risk: 'Medium', upgrades: [] },
  { name: 'Laser tag arena', price: 450000, risk: 'Medium', upgrades: [] },
  { name: 'Paintball field', price: 350000, risk: 'Medium', upgrades: [] },
  { name: 'Co-working space', price: 800000, risk: 'Medium', upgrades: [] },
  { name: 'Marketing agency', price: 150000, risk: 'Low', upgrades: [] },
  { name: 'PR firm', price: 200000, risk: 'Low', upgrades: [] },
  { name: 'Law firm', price: 500000, risk: 'Medium', upgrades: [] },
  { name: 'Accounting firm', price: 300000, risk: 'Low', upgrades: [] },
  { name: 'Dental clinic', price: 800000, risk: 'Medium', upgrades: [] },
  { name: 'Private school', price: 4000000, risk: 'High', upgrades: [] },
  { name: 'E-commerce store', price: 250000, risk: 'Medium', upgrades: [] },
  { name: 'Subscription box company', price: 300000, risk: 'Medium', upgrades: [] },
  { name: 'Food delivery service', price: 500000, risk: 'High', upgrades: [] },
  { name: 'Taxi company', price: 1000000, risk: 'Medium', upgrades: [] },
  { name: 'Ride-sharing startup', price: 2000000, risk: 'High', upgrades: [] },
  { name: 'Travel agency', price: 150000, risk: 'Low', upgrades: [] },
  { name: 'Event planning company', price: 200000, risk: 'Low', upgrades: [] },
  { name: 'Wedding business', price: 350000, risk: 'Medium', upgrades: [] },
  { name: 'Catering company', price: 400000, risk: 'Medium', upgrades: [] },
  { name: 'Construction firm', price: 1500000, risk: 'High', upgrades: [] },
  { name: 'Interior design firm', price: 250000, risk: 'Low', upgrades: [] },
  { name: 'Real estate agency', price: 300000, risk: 'Medium', upgrades: [] },
  { name: 'Import/export business', price: 800000, risk: 'High', upgrades: [] },
  { name: 'Security company', price: 500000, risk: 'Medium', upgrades: [] },
  { name: 'Cleaning company (large)', price: 400000, risk: 'Medium', upgrades: [] },
  { name: 'Fitness brand', price: 600000, risk: 'Medium', upgrades: [] },
  { name: 'Sports academy', price: 800000, risk: 'Medium', upgrades: [] },
  { name: 'Music production studio', price: 1000000, risk: 'High', upgrades: [] },
  { name: 'Influencer agency', price: 250000, risk: 'Medium', upgrades: [] },
  { name: 'Publishing company', price: 500000, risk: 'Medium', upgrades: [] },
  { name: 'Book publisher', price: 400000, risk: 'Medium', upgrades: [] },
  { name: 'Magazine company', price: 300000, risk: 'Medium', upgrades: [] },
  { name: 'Online course platform', price: 200000, risk: 'Low', upgrades: [] },
  { name: 'App development company', price: 350000, risk: 'Medium', upgrades: [] },
  { name: 'Software company', price: 1000000, risk: 'High', upgrades: [] },
  { name: 'Cybersecurity firm', price: 800000, risk: 'High', upgrades: [] },
  { name: 'Data analytics company', price: 600000, risk: 'Medium', upgrades: [] },
  { name: 'Cloud service company', price: 2000000, risk: 'High', upgrades: [] },
  { name: 'Tech repair chain', price: 750000, risk: 'Medium', upgrades: [] },
  { name: 'Gaming lounge chain', price: 1200000, risk: 'Medium', upgrades: [] }
];

const largeBusinesses = [
  { name: 'Hotel (small)', price: 3000000, risk: 'Medium', upgrades: [
    { id: 'u1', name: 'Luxury rooms', costMultiplier: 0.3, profitBoost: 0.08 },
    { id: 'u2', name: 'Events hosting', costMultiplier: 0.4, profitBoost: 0.1 },
    { id: 'u3', name: 'Spa', costMultiplier: 0.5, profitBoost: 0.12 },
    { id: 'u4', name: 'Chain expansion', costMultiplier: 1.5, profitBoost: 0.4 },
  ]},
  { name: 'Shopping Mall', price: 10000000, risk: 'High', upgrades: [] },
  { name: 'Factory', price: 5000000, risk: 'Medium', upgrades: [] },
  { name: 'Airline (small regional)', price: 10000000, risk: 'High', upgrades: [
    { id: 'u1', name: 'Buy new planes', costMultiplier: 0.5, profitBoost: 0.12 },
    { id: 'u2', name: 'Add routes', costMultiplier: 0.4, profitBoost: 0.1 },
    { id: 'u3', name: 'Upgrade classes', costMultiplier: 0.3, profitBoost: 0.08 },
    { id: 'u4', name: 'Cargo division', costMultiplier: 0.8, profitBoost: 0.2 },
  ]},
  { name: 'Construction Company', price: 2000000, risk: 'High', upgrades: [] },
  { name: 'Logistics Company', price: 4000000, risk: 'Medium', upgrades: [] },
  { name: 'Tech Company', price: 500000, risk: 'Very High', upgrades: [
    { id: 'u1', name: 'Launch product', costMultiplier: 0.3, profitBoost: 0.08 },
    { id: 'u2', name: 'Hire engineers', costMultiplier: 0.4, profitBoost: 0.1 },
    { id: 'u3', name: 'Sell licenses', costMultiplier: 0.5, profitBoost: 0.12 },
    { id: 'u4', name: 'Go public', costMultiplier: 2.0, profitBoost: 0.5 },
  ]},
  { name: 'Game Studio', price: 250000, risk: 'Very High', upgrades: [] },
  { name: 'Real Estate Company', price: 1500000, risk: 'Medium', upgrades: [] },
  { name: 'Investment Firm', price: 2000000, risk: 'High', upgrades: [] },
  // 60 more large businesses
  { name: 'Airline (full)', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Airport services', price: 20000000, risk: 'Medium', upgrades: [] },
  { name: 'Shipping company', price: 10000000, risk: 'Medium', upgrades: [] },
  { name: 'Railway company', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Oil refinery', price: 100000000, risk: 'High', upgrades: [] },
  { name: 'Mining company', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Energy company', price: 100000000, risk: 'High', upgrades: [] },
  { name: 'Solar farm', price: 20000000, risk: 'Medium', upgrades: [] },
  { name: 'Wind farm', price: 30000000, risk: 'Medium', upgrades: [] },
  { name: 'Water company', price: 10000000, risk: 'Low', upgrades: [] },
  { name: 'Telecom company', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Internet provider', price: 20000000, risk: 'Medium', upgrades: [] },
  { name: 'TV network', price: 100000000, risk: 'High', upgrades: [] },
  { name: 'Streaming service', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Film production company', price: 20000000, risk: 'Medium', upgrades: [] },
  { name: 'Record label', price: 10000000, risk: 'Medium', upgrades: [] },
  { name: 'Luxury hotel chain', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Theme park', price: 100000000, risk: 'High', upgrades: [] },
  { name: 'Zoo', price: 20000000, risk: 'Medium', upgrades: [] },
  { name: 'Aquarium', price: 10000000, risk: 'Medium', upgrades: [] },
  { name: 'Cruise company', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Space tourism', price: 200000000, risk: 'Very High', upgrades: [] },
  { name: 'Private jet company', price: 30000000, risk: 'High', upgrades: [] },
  { name: 'Defense contractor', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Automotive company', price: 100000000, risk: 'High', upgrades: [] },
  { name: 'Electric car company', price: 500000000, risk: 'Very High', upgrades: [] },
  { name: 'AI company', price: 100000000, risk: 'Very High', upgrades: [] },
  { name: 'Robotics company', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Biotech company', price: 100000000, risk: 'High', upgrades: [] },
  { name: 'Pharmaceutical company', price: 500000000, risk: 'High', upgrades: [] },
  { name: 'Bank', price: 100000000, risk: 'Medium', upgrades: [] },
  { name: 'Investment bank', price: 200000000, risk: 'High', upgrades: [] },
  { name: 'Hedge fund', price: 500000000, risk: 'Very High', upgrades: [] },
  { name: 'Insurance company', price: 100000000, risk: 'Medium', upgrades: [] },
  { name: 'Stock exchange', price: 50000000, risk: 'Medium', upgrades: [] },
  { name: 'Real estate developer', price: 100000000, risk: 'High', upgrades: [] },
  { name: 'Mega mall', price: 200000000, risk: 'High', upgrades: [] },
  { name: 'Skyscraper developer', price: 500000000, risk: 'High', upgrades: [] },
  { name: 'Global logistics', price: 100000000, risk: 'Medium', upgrades: [] },
  { name: 'Food corporation', price: 100000000, risk: 'Medium', upgrades: [] }
];

const ultraRichBusinesses = [
  { name: 'Oil Company', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Private Bank', price: 20000000, risk: 'Medium', upgrades: [] },
  { name: 'Luxury Brand', price: 5000000, risk: 'High', upgrades: [] },
  { name: 'Space Company', price: 100000000, risk: 'Very High', upgrades: [
    { id: 'u1', name: 'Rocket upgrades', costMultiplier: 0.5, profitBoost: 0.12 },
    { id: 'u2', name: 'Government contracts', costMultiplier: 0.4, profitBoost: 0.1 },
    { id: 'u3', name: 'Tourism', costMultiplier: 0.8, profitBoost: 0.2 },
    { id: 'u4', name: 'Mars mission', costMultiplier: 2.0, profitBoost: 0.5 },
  ]},
  { name: 'Private Military Company', price: 10000000, risk: 'Very High', upgrades: [] },
  { name: 'Film Studio', price: 20000000, risk: 'High', upgrades: [] },
  { name: 'Streaming Platform', price: 10000000, risk: 'High', upgrades: [] },
  { name: 'Casino', price: 15000000, risk: 'High', upgrades: [
    { id: 'u1', name: 'VIP rooms', costMultiplier: 0.3, profitBoost: 0.08 },
    { id: 'u2', name: 'Online gambling', costMultiplier: 0.5, profitBoost: 0.12 },
    { id: 'u3', name: 'Events', costMultiplier: 0.4, profitBoost: 0.1 },
    { id: 'u4', name: 'Security', costMultiplier: 0.2, profitBoost: 0.05 },
  ]},
  { name: 'Cruise Line', price: 50000000, risk: 'High', upgrades: [] },
  { name: 'Private Island Resort', price: 25000000, risk: 'Medium', upgrades: [] },
  // 30 more ultra rich businesses
  { name: 'Private island empire', price: 500000000, risk: 'Medium', upgrades: [] },
  { name: 'Global airline alliance', price: 1000000000, risk: 'High', upgrades: [] },
  { name: 'Space colony company', price: 2000000000, risk: 'Very High', upgrades: [] },
  { name: 'Mega tech empire', price: 5000000000, risk: 'High', upgrades: [] },
  { name: 'Luxury fashion empire', price: 1000000000, risk: 'High', upgrades: [] },
  { name: 'Global media empire', price: 2000000000, risk: 'High', upgrades: [] },
  { name: 'Oil empire', price: 5000000000, risk: 'High', upgrades: [] },
  { name: 'Crypto exchange', price: 1000000000, risk: 'Very High', upgrades: [] },
  { name: 'Metaverse company', price: 2000000000, risk: 'Very High', upgrades: [] },
  { name: 'AI supercompany', price: 5000000000, risk: 'Very High', upgrades: [] },
  { name: 'Military contractor empire', price: 1000000000, risk: 'High', upgrades: [] },
  { name: 'Planet mining company', price: 2000000000, risk: 'Very High', upgrades: [] },
  { name: 'Global shipping empire', price: 5000000000, risk: 'High', upgrades: [] },
  { name: 'Casino empire', price: 1000000000, risk: 'High', upgrades: [] },
  { name: 'Resort empire', price: 2000000000, risk: 'Medium', upgrades: [] },
  { name: 'Entertainment empire', price: 5000000000, risk: 'High', upgrades: [] },
  { name: 'Sports league owner', price: 1000000000, risk: 'Medium', upgrades: [] },
  { name: 'International bank', price: 2000000000, risk: 'Medium', upgrades: [] },
  { name: 'World trade company', price: 5000000000, risk: 'Medium', upgrades: [] },
  { name: 'Global construction empire', price: 1000000000, risk: 'High', upgrades: [] }
];

const generateUniqueUpgrades = (businessName: string) => {
  return [
    { id: 'u1', name: 'Targeted Marketing', costMultiplier: 0.2, profitBoost: 0.05 },
    { id: 'u2', name: 'Brand Expansion', costMultiplier: 0.4, profitBoost: 0.1 },
    { id: 'u3', name: 'VIP Services', costMultiplier: 0.6, profitBoost: 0.15 },
    { id: 'u4', name: 'Global Licensing', costMultiplier: 1.0, profitBoost: 0.25 },
  ];
};

const generateBusinesses = (list: any[], category: 'Small' | 'Medium' | 'Large' | 'Ultra Rich', defaultPrice: number, defaultRisk: 'Low' | 'Medium' | 'High' | 'Very High'): BusinessDefinition[] => {
  return list.map((item, index) => {
    if (typeof item === 'string') {
      return {
        id: `${category.toLowerCase().replace(' ', '_')}_${index}`,
        name: item,
        category,
        basePrice: defaultPrice,
        riskLevel: defaultRisk,
        uniqueUpgrades: generateUniqueUpgrades(item)
      };
    } else {
      return {
        id: `${category.toLowerCase().replace(' ', '_')}_${index}`,
        name: item.name,
        category,
        basePrice: item.price,
        riskLevel: item.risk as any,
        uniqueUpgrades: item.upgrades.length > 0 ? item.upgrades : generateUniqueUpgrades(item.name)
      };
    }
  });
};

export const BUSINESSES: BusinessDefinition[] = [
  ...generateBusinesses(smallBusinesses, 'Small', 15000, 'Low'),
  ...generateBusinesses(mediumBusinesses, 'Medium', 200000, 'Medium'),
  ...generateBusinesses(largeBusinesses, 'Large', 5000000, 'High'),
  ...generateBusinesses(ultraRichBusinesses, 'Ultra Rich', 20000000, 'Very High')
];
